-- Support Oracle database creation full script     
--  
-- Version: 8.6.1
-- Internal Version: 8.6.1.2
-- 
-- Edit History:
--  
-- Date         IssueID             Fix          	Reason
-- ==========   ==================  ===========  	====================================================
-- 19/05/2022	DTS_DT853			Surachai C.		[DTS_DT853] DT/MT 8.5.3
-- 17/10/2022	DTS_DT861			Surachai C.		[DTS_DT861] DT/MT 8.6.1


SET TIMING ON;
SET SQLBLANKLINES ON;
SET SERVEROUTPUT ON SIZE 1000000;
WHENEVER OSERROR EXIT FAILURE ROLLBACK;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

CREATE TABLESPACE DT_ARCHIVE8N DATAFILE 'DT_ARCHIVE8N.dbf' SIZE 500M AUTOEXTEND ON NEXT  50M MAXSIZE UNLIMITED;

CREATE TEMPORARY TABLESPACE TEMP_SPACE8N TEMPFILE 'TEMP_SPACE8N.dbf' SIZE 50M AUTOEXTEND ON NEXT  5M MAXSIZE UNLIMITED;

CREATE TABLESPACE INDEX_SPACE8N DATAFILE 'INDEX_SPACE8N.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

CREATE USER C##RTR_DT8N  PROFILE "DEFAULT" IDENTIFIED BY "reut" DEFAULT TABLESPACE DT_ARCHIVE8N TEMPORARY TABLESPACE TEMP_SPACE8N ACCOUNT UNLOCK;
GRANT "CONNECT" TO C##RTR_DT8N;
ALTER USER C##RTR_DT8N DEFAULT ROLE ALL;
ALTER USER C##RTR_DT8N QUOTA UNLIMITED ON DT_ARCHIVE8N;
ALTER USER C##RTR_DT8N QUOTA UNLIMITED ON INDEX_SPACE8N;

GRANT CREATE JOB TO C##RTR_DT8N;

CREATE TABLE C##RTR_DT8N.CONVERSATIONS (
	TCID CHAR(4) NULL,
	SOURCEREFERENCE CHAR(11) NOT NULL,
	SOURCEOFDATA NUMBER(3) NULL,
	TIMEOFDEAL DATE NOT NULL,
	DEALERID VARCHAR2(40) NULL,
	BANK1DEALINGCODE CHAR(4) NULL,
	BANK1NAME NVARCHAR2(56) NULL,
	BROKERDEALINGCODE CHAR(4) NULL,
	BROKERNAME CHAR(56) NULL,
	DEALTYPE NUMBER(3) NULL,
	PERIOD1 NUMBER(5) NULL,
	PERIOD2 NUMBER(5) NULL,
	CURRENCY1 CHAR(3) NULL,
	CURRENCY2 CHAR(3) NULL,
	DEALVOLUMECURRENCY1 NUMBER(38,17) NULL,
	DEPOSITRATE NUMBER(38,17) NULL,
	SWAPRATE NUMBER(38,17) NULL,
	EXCHANGERATEPERIOD1 NUMBER(38,17) NULL,
	EXCHANGERATEPERIOD2 NUMBER(38,17) NULL,
	RATEDIRECTION NUMBER(3) NULL,
	VALUEDATEPERIOD1CURRENCY1 DATE NULL,
	VALUEDATEPERIOD1CURRENCY2 DATE NULL,
	VALUEDATEPERIOD2CURRENCY1 DATE NULL,
	VALUEDATEPERIOD2CURRENCY2 DATE NULL,
	DEALERNAME CHAR(20) NULL,
	LOCALTCID CHAR(4) NULL,
	REVIEWREFERENCENUMBER VARCHAR2(100) NULL,
	FRAFIXINGDATE DATE NULL,
	FRASETTLEMENTDATE DATE NULL,
	FRAMATURITYDATE DATE NULL,
	IMMINDICATOR NUMBER(3) NULL,
	OUTRIGHTPOINTSPREMIUMRATE NUMBER(38,17) NULL,
	SPOTBASISRATE NUMBER(38,17) NULL,
	PUREDEALTYPE NUMBER(10) NULL,
	BID NUMBER(38,17) NULL,
	OFFER NUMBER(38,17) NULL,
	CONVERSATIONSTATUS NUMBER(3) NULL,
	TICKETSTATUS NUMBER(3) NULL,
	RATESTATUS NUMBER(3) NULL,
	CONVERSATIONTEXT CLOB NULL,
	QUOTESTATUS NUMBER(3) NULL,
	INITIATOR NUMBER(3) NULL,
	NODEAL NUMBER(1) DEFAULT 0 NULL,
	TEXTCHECKSUM NUMBER(10) DEFAULT 0 NULL,
	CUSTOMDEALINGFIELD1 VARCHAR2(200) NULL,
	CUSTOMDEALINGFIELD2 VARCHAR2(200) NULL,
	CUSTOMDEALINGFIELD3 VARCHAR2(200) NULL,
	ARCHIVETIME DATE DEFAULT SYSDATE NOT NULL,
	NODEALEDBY VARCHAR2(200) NULL,
	MIDOFFICECOMMENT VARCHAR2(200) NULL,
	REVIEWEDBYID VARCHAR2(255) NULL,
	REVIEWEDBYNAME VARCHAR2(30) NULL,
	REVIEWEDAT DATE NULL,
	TRANSACTIONID VARCHAR2(52) NULL,
	STARTDATE  DATE NULL,
	ENDDATE DATE NULL,
	DELIVERYDATE DATE NULL,
	DELIVERYDATE2 DATE NULL,
	EXPIRYDATE DATE NULL,
	EXPIRYDATE2 DATE NULL,
	PAYMENTDATE DATE NULL,
	PREMIUMDATE DATE NULL,
	INTERESTDAYBASIS VARCHAR2(10) NULL, 
	INTERESTDAYBASIS2 VARCHAR2(10) NULL, 
	INDEX1 VARCHAR2(20) NULL, 
	INDEX2 VARCHAR2(20) NULL, 
	RESETFREQUENCY NUMBER(3) NULL, 
	RESETBUSINESSDAYCONVENTION NUMBER(2) NULL, 
	PAYMENTBUSINESSDAYCONVENTION NUMBER(2) NULL, 
	RESETCALENDAR VARCHAR2(20) NULL, 
	PAYMENTFREQUENCY NUMBER(3) NULL, 
	SECONDARYFREQUENCY NUMBER(3) NULL, 
	STUBINDICATOR VARCHAR2(20) NULL, 
	STUBRATE NUMBER(38,17) NULL, 
	INDEXSPREAD NUMBER(38,17) NULL, 
	OPTIONTYPE VARCHAR2(10) NULL, 
	OPTIONTYPE2 VARCHAR2(10) NULL, 
	CUTOFF VARCHAR2(20) NULL, 
	CUTOFF2 VARCHAR2(20) NULL, 
	EXPIRYSTYLE NUMBER(2) NULL, 
	DIRECTION2 NUMBER(2) NULL, 
	TRADINGSTRATEGY NUMBER(2) NULL, 
	SETTLEMENT NUMBER(2) NULL, 
	PREMIUMAMOUNT NUMBER(38,17) NULL, 
	PREMIUMAMOUNT2 NUMBER(38,17) NULL, 
	VOLATILITY NUMBER(38,17) NULL, 
	VOLATILITY2 NUMBER(38,17) NULL, 
	PREMIUMQUOTE NUMBER(38,17) NULL, 
	PREMIUMQUOTE2 NUMBER(38,17) NULL, 
	PREMIUMCURRENCY VARCHAR2(3) NULL, 
	TOTALNETPREMIUMAMOUNT NUMBER(38,17) NULL, 
	PREMIUMQUOTECONVENTION NUMBER(2) NULL, 
	HEDGEDIRECTION NUMBER(2) NULL, 
	HEDGEDIRECTION2 NUMBER(2) NULL, 
	HEDGEVALUEDATE DATE NULL, 
	HEDGEVALUEDATE2 DATE NULL, 
	HEDGEAMOUNT NUMBER(38,17) NULL, 
	HEDGEAMOUNT2 NUMBER(38,17) NULL, 
	HEDGECONTRAAMOUNT NUMBER(38,17) NULL, 
	HEDGECONTRAAMOUNT2 NUMBER(38,17) NULL, 
	HEDGERATE NUMBER(38,17) NULL, 
	HEDGERATE2 NUMBER(38,17) NULL,
	DTFEID NUMBER(18) NULL,
	DEPOSITRATEREFERENCE NUMBER(38,17) NULL,
	DEPOSITRATEREFERENCE2 NUMBER(38,17) NULL,
	SWAPPOINTSREFERENCE NUMBER(38,17) NULL,
	SWAPPOINTSREFERENCE2 NUMBER(38,17) NULL,
	SWIFTBICC1P1 VARCHAR2(11) NULL, 
	SWIFTBICC1P2 VARCHAR2(11) NULL,
	SWIFTBICC2P1 VARCHAR2(11) NULL,
	SWIFTBICC2P2 VARCHAR2(11) NULL,
	PAYMENTINSTRUCTIONP1C1 NVARCHAR2(80) NULL,
	PAYMENTINSTRUCTIONP1C2 NVARCHAR2(80) NULL,
	PAYMENTINSTRUCTIONP2C1 NVARCHAR2(80) NULL,
	PAYMENTINSTRUCTIONP2C2 NVARCHAR2(80) NULL,
	FIXEDRATE NUMBER(38,17) NULL,
	CALVOLUMEP2C1 NUMBER(38,17) NULL,
	CUSTOMDEALINGFIELD4 VARCHAR2(200) NULL, 
	CUSTOMDEALINGFIELD5 VARCHAR2(200) NULL, 
	CUSTOMDEALINGFIELD6 VARCHAR2(200) NULL,
	INTERESTVOLUME NUMBER(38,17) NULL,
	ELAPSEDDAYS NUMBER(10) NULL,
	YEARLENGTH NUMBER(10) NULL,
	PRICECONVENTION NUMBER(10) NULL,
	CLEARINGHOUSE VARCHAR2(20) NULL,
	OURCLEARINGMEMBER VARCHAR2(40) NULL,
	THEIRCLEARINGMEMBER VARCHAR2(40) NULL,
	ONBEHALFOFNAME VARCHAR2(64) NULL,
	ONBEHALFOFCODE VARCHAR2(4) NULL,
	PREMIUMDATE2 DATE NULL,
	PROCESSED NUMBER(3) DEFAULT 0,
	PROCESSEDBY VARCHAR2(200) NULL,
	PROCESSEDAT DATE NULL,
	PROCESSED2 NUMBER(3) DEFAULT 0,
	PROCESSED2BY VARCHAR2(200) NULL,
	PROCESSED2AT DATE NULL,
	MIDPRICE NUMBER(38,17) NULL,
	BESTBID NUMBER(38,17) NULL,
	BESTASK NUMBER(38,17) NULL,
	OURLEI VARCHAR2(20) NULL,
	THEIRLEI VARCHAR2(20) NULL,	
	BROKERAGEAMOUNT NUMBER(38,17) NULL,
	REPORTINGPARTY VARCHAR2(40) NULL,
	NAMESPACE VARCHAR2(20) NULL,
	LINKID VARCHAR2(52) NULL,
	TRANSACTIONID2 VARCHAR2(52) NULL,
	TRADEREPOSITORY VARCHAR2(40) NULL,
	BROKERAGECURRENCY VARCHAR2(3) NULL,
	CLEARINGACCOUNT VARCHAR2(40) NULL,
	CPUSERID VARCHAR2(40) NULL,
	CPUSERNAME VARCHAR2(40) NULL,
	UTI1 VARCHAR2(52) NULL,
	UTI2 VARCHAR2(52) NULL,
	PRINTED NUMBER(5) DEFAULT 0 NOT NULL,
	OUREMAILADDRESS VARCHAR2(256) NULL,
	THEIREMAILADDRESS VARCHAR2(256) NULL,
	TRADINGINTERFACE VARCHAR2(80) NULL,
	BENCHMARKFIXINGTYPE1 VARCHAR2(20) NULL,
	BENCHMARKFIXINGDATE1 DATE NULL,
	BENCHMARKFIXINGRATE1 VARCHAR2(38) NULL,
	BENCHMARKFIXINGTYPE2 VARCHAR2(20) NULL,
	BENCHMARKFIXINGDATE2 DATE NULL,
	BENCHMARKFIXINGRATE2 VARCHAR2(38) NULL,
	OURJURISDICTION VARCHAR2(280) NULL,
	THEIRJURISDICTION VARCHAR2(280) NULL,
	EXECUTIONVENUETYPE VARCHAR2(280) NULL,
	OURCLEARINGBROKER VARCHAR2(4) NULL,
	OURCLEARINGBROKERLEI VARCHAR2(20) NULL,
	THEIRCLEARINGBROKER VARCHAR2(4) NULL,
	THEIRCLEARINGBROKERLEI VARCHAR2(20) NULL,
	EXECUTIONID VARCHAR2(100) NULL,
	ORDERID VARCHAR2(100) NULL,
	CALLINITTIME TIMESTAMP NULL,
	ACCEPTTIME TIMESTAMP NULL,
	CONFIRMEDTIME TIMESTAMP NULL,
	EXTRACTEDTIME TIMESTAMP NULL,
	FIRSTENDTIME TIMESTAMP NULL,
	SECONDENDTIME TIMESTAMP NULL,
	QUOTETIME TIMESTAMP NULL,
	QUOTEREJECTTIME TIMESTAMP NULL,
	AGGRESSORINDICATOR NUMBER(3) DEFAULT -1 NULL,
	CONSTRAINT UN_CONVERSATIONS UNIQUE (LOCALTCID, SOURCEREFERENCE, TIMEOFDEAL, TEXTCHECKSUM)
) TABLESPACE DT_ARCHIVE8N;

CREATE INDEX C##RTR_DT8N.Conversations_CCY1 ON C##RTR_DT8N.Conversations(CURRENCY1) TABLESPACE INDEX_SPACE8N;
CREATE INDEX C##RTR_DT8N.Conversations_CCY2 ON C##RTR_DT8N.Conversations(CURRENCY2) TABLESPACE INDEX_SPACE8N;
CREATE INDEX C##RTR_DT8N.Conversations_DType ON C##RTR_DT8N.Conversations(PUREDEALTYPE, DEALTYPE) TABLESPACE INDEX_SPACE8N;
CREATE INDEX C##RTR_DT8N.Conversations_Logon ON C##RTR_DT8N.Conversations(LOCALTCID, DEALERID, DEALERNAME) TABLESPACE INDEX_SPACE8N;
CREATE INDEX C##RTR_DT8N.Conversations_Dealer ON C##RTR_DT8N.Conversations(DEALERID) TABLESPACE INDEX_SPACE8N;
CREATE INDEX C##RTR_DT8N.Conversations_NoDeal ON C##RTR_DT8N.Conversations(NODEAL) TABLESPACE INDEX_SPACE8N;
CREATE INDEX C##RTR_DT8N.Conversations_SR ON C##RTR_DT8N.Conversations(SOURCEREFERENCE) TABLESPACE INDEX_SPACE8N;
CREATE INDEX C##RTR_DT8N.Conversations_TCID ON C##RTR_DT8N.Conversations(BANK1DEALINGCODE) TABLESPACE INDEX_SPACE8N;
CREATE INDEX C##RTR_DT8N.Conversations_TOD ON C##RTR_DT8N.Conversations(TIMEOFDEAL) TABLESPACE INDEX_SPACE8N;
CREATE INDEX C##RTR_DT8N.Conversations_COVERIDX1 ON C##RTR_DT8N.Conversations(SOURCEREFERENCE, TCID, TIMEOFDEAL, TICKETSTATUS, NODEAL) TABLESPACE INDEX_SPACE8N;
CREATE INDEX C##RTR_DT8N.Conversations_DTFEID ON C##RTR_DT8N.Conversations(DTFEID) TABLESPACE INDEX_SPACE8N;
CREATE INDEX C##RTR_DT8N.Conversations_ARCHIVETIME ON C##RTR_DT8N.Conversations(ARCHIVETIME) TABLESPACE INDEX_SPACE8N;
CREATE INDEX C##RTR_DT8N.Conversations_Processed ON C##RTR_DT8N.Conversations(PROCESSED) TABLESPACE INDEX_SPACE8N;



CREATE TABLE C##RTR_DT8N.TICKETS(
	DEALID CHAR(15) NULL,
	PROCESSED NUMBER(3) DEFAULT 0,
	PROCESSEDBY VARCHAR2(200) NULL,
	PROCESSEDAT DATE NULL,
	PROCESSED2 NUMBER(3) DEFAULT 0,
	PROCESSED2BY VARCHAR2(200) NULL,
	PROCESSED2AT DATE NULL,
	LASTMODIFIEDBY VARCHAR2(200) NULL,
	LASTMODIFIEDAT DATE NULL,
	LOCALTCID CHAR(4) NULL,
	SOURCEREFERENCE CHAR(11) NOT NULL,
	TIMEOFDEAL DATE NOT NULL,
	DEALERID VARCHAR2(40) NULL,
	PUREDEALTYPE NUMBER(10) NULL,
	DEALTYPE NUMBER(3) NULL,
	BANK1DEALINGCODE CHAR(4) NULL,
	BROKERDEALINGCODE CHAR(4) NULL,
	CURRENCY1 CHAR(3) NULL,
	CURRENCY2 CHAR(3) NULL,
	DEALVOLUMECURRENCY1 NUMBER(38,17) NULL,
	EXCHANGERATEPERIOD1 NUMBER(38,17) NULL,
	EXCHANGERATEPERIOD2 NUMBER(38,17) NULL,
	METHODOFDEAL NUMBER(3) NULL,
	PERIOD1 NUMBER(5) NULL,
	PERIOD2 NUMBER(5) NULL,
	CONFIRMATIONTIME DATE NULL,
	CONFIRMEDBYID CHAR(40) NULL,
	BASECURRENCY CHAR(3) NULL,
	BANK1NAME NVARCHAR2(56) NULL,
	DEPOSITRATE NUMBER(38,17) NULL,
	SWAPRATE NUMBER(38,17) NULL,
	SOURCEOFDATA NUMBER(3) NULL,
	RATEDIRECTION NUMBER(3) NULL,
	VALUEDATEPERIOD1CURRENCY1 DATE NULL,
	VALUEDATEPERIOD1CURRENCY2 DATE NULL,
	VALUEDATEPERIOD2CURRENCY1 DATE NULL,
	VALUEDATEPERIOD2CURRENCY2 DATE NULL,
	DEALERNAME CHAR(20) NULL,
	REVIEWREFERENCENUMBER VARCHAR2(100) NULL,
	BROKERNAME CHAR(56) NULL,
	FRAFIXINGDATE DATE NULL,
	FRASETTLEMENTDATE DATE NULL,
	FRAMATURITYDATE DATE NULL,
	IMMINDICATOR NUMBER(3) NULL,
	OUTRIGHTPOINTSPREMIUMRATE NUMBER(38,17) NULL,
	SPOTBASISRATE NUMBER(38,17) NULL,
	CONVERSATIONTEXT CLOB NULL,
	PAYMENTINSTRUCTIONP1C1 NVARCHAR2(80) NULL,
	PAYMENTINSTRUCTIONP1C2 NVARCHAR2(80) NULL,
	PAYMENTINSTRUCTIONP2C1 NVARCHAR2(80) NULL,
	PAYMENTINSTRUCTIONP2C2 NVARCHAR2(80) NULL,
	SECONDARYSOURCEREF CHAR(56) NULL,
	RATEC1USD NUMBER(38,17) NULL,
	RATEC2USD NUMBER(38,17) NULL,
	RATEBASECUSD NUMBER(38,17) NULL,
	CALVOLUMEP1C2 NUMBER(38,17) NULL,
	CALVOLUMEP2C2 NUMBER(38,17) NULL,
	CALVOLUMEP2C1 NUMBER(38,17) NULL,
	CONFIRMEDBYNAME CHAR(30) NULL,
	COMMENTTEXT CHAR(124) NULL,
	USERDEFINEDTITLE1 CHAR(20) NULL,
	USERDEFINEDDATA1 NVARCHAR2(40) NULL,
	USERDEFINEDTITLE2 CHAR(20) NULL,
	USERDEFINEDDATA2 NVARCHAR2(40) NULL,
	USERDEFINEDTITLE3 CHAR(20) NULL,
	USERDEFINEDDATA3 NVARCHAR2(40) NULL,
	IDIFCONTRA CHAR(11) NULL,
	IDPREVIOUS CHAR(11) NULL,
	INTERESTVOLUME NUMBER(38,17) NULL,
	ELAPSEDDAYS NUMBER(10) NULL,
	YEARLENGTH NUMBER(10) NULL,
	PRICECONVENTION NUMBER(10) NULL,
	SWIFTBICC1P1 VARCHAR2(11) NULL,
	SWIFTBICC1P2 VARCHAR2(11) NULL,
	SWIFTBICC2P1 VARCHAR2(11) NULL,
	SWIFTBICC2P2 VARCHAR2(11) NULL,
	CREDITREDUCTION NUMBER(38,17) NULL,
	CREDITREMAINING NUMBER(38,17) NULL,
	BASECURRENCY2 CHAR(3) NULL,
	BASECURRENCY3 CHAR(3) NULL,
	RATEBASEC2USD NUMBER(38,17) NULL,
	RATEBASEC3USD NUMBER(38,17) NULL,
	SCOPE NUMBER(10) DEFAULT -1 NULL,
	CUSTOMDEALINGFIELD1 VARCHAR2(200) NULL,
	CUSTOMDEALINGFIELD2 VARCHAR2(200) NULL,
	CUSTOMDEALINGFIELD3 VARCHAR2(200) NULL,
	MIDOFFICECOMMENT VARCHAR2(200) NULL,
	AUTOGENERATEDTICKET NUMBER(3) NULL,
	TRANSACTIONID VARCHAR2(52) NULL,
	STARTDATE DATE NULL,
	ENDDATE DATE NULL,
	DELIVERYDATE DATE NULL,
	DELIVERYDATE2 DATE NULL,
	EXPIRYDATE DATE NULL,
	EXPIRYDATE2 DATE NULL,
	PAYMENTDATE DATE NULL,
	PREMIUMDATE DATE NULL,
	INTERESTDAYBASIS VARCHAR2(20) NULL,
	INTERESTDAYBASIS2 VARCHAR2(20) NULL,
	INDEX1 VARCHAR2(20) NULL,
	INDEX2 VARCHAR2(20) NULL,
	RESETFREQUENCY NUMBER(3) NULL,
	RESETBUSINESSDAYCONVENTION NUMBER(2) NULL,
	PAYMENTBUSINESSDAYCONVENTION NUMBER(2) NULL,
	RESETCALENDAR VARCHAR2(20) NULL,
	PAYMENTFREQUENCY NUMBER(3) NULL,
	SECONDARYFREQUENCY NUMBER(3) NULL,
	STUBINDICATOR VARCHAR2(20) NULL,
	STUBRATE NUMBER(38,17) NULL,
	INDEXSPREAD NUMBER(38,17) NULL,
	OPTIONTYPE VARCHAR2(10) NULL,
	OPTIONTYPE2 VARCHAR2(10) NULL,
	CUTOFF VARCHAR2(20) NULL,
	CUTOFF2 VARCHAR2(20) NULL,
	EXPIRYSTYLE NUMBER(2) NULL,
	DIRECTION2 NUMBER(2) NULL,
	TRADINGSTRATEGY NUMBER(2) NULL,
	SETTLEMENT NUMBER(2) NULL,
	PREMIUMAMOUNT NUMBER(38,17) NULL,
	PREMIUMAMOUNT2 NUMBER(38,17) NULL,
	VOLATILITY NUMBER(38,17) NULL,
	VOLATILITY2 NUMBER(38,17) NULL,
	PREMIUMQUOTE NUMBER(38,17) NULL,
	PREMIUMQUOTE2 NUMBER(38,17) NULL,
	PREMIUMCURRENCY VARCHAR2(3) NULL,
	TOTALNETPREMIUMAMOUNT NUMBER(38,17) NULL,
	PREMIUMQUOTECONVENTION NUMBER(2) NULL,
	HEDGEDIRECTION NUMBER(2) NULL,
	HEDGEDIRECTION2 NUMBER(2) NULL,
	HEDGEVALUEDATE DATE NULL,
	HEDGEVALUEDATE2 DATE NULL,
	HEDGEAMOUNT NUMBER(38,17) NULL,
	HEDGEAMOUNT2 NUMBER(38,17) NULL,
	HEDGECONTRAAMOUNT NUMBER(38,17) NULL,
	HEDGECONTRAAMOUNT2 NUMBER(38,17) NULL,
	HEDGERATE NUMBER(38,17) NULL,
	HEDGERATE2 NUMBER(38,17) NULL,
	DEPOSITRATEREFERENCE NUMBER(38,17) NULL,
	DEPOSITRATEREFERENCE2 NUMBER(38,17) NULL,
	SWAPPOINTSREFERENCE NUMBER(38,17) NULL,
	SWAPPOINTSREFERENCE2 NUMBER(38,17) NULL,
	FIXEDRATE NUMBER(38,17) NULL,
	BANK2NAME VARCHAR2(56) NULL,
	CUSTOMDEALINGFIELD4 VARCHAR2(200) NULL,
	CUSTOMDEALINGFIELD5 VARCHAR2(200) NULL,
	CUSTOMDEALINGFIELD6 VARCHAR2(200) NULL,
	CLEARINGHOUSE VARCHAR2(20) NULL,
	OURCLEARINGMEMBER VARCHAR2(40) NULL,
	THEIRCLEARINGMEMBER VARCHAR2(40) NULL,
	ONBEHALFOFNAME VARCHAR2(64) NULL,
	ONBEHALFOFCODE VARCHAR2(4) NULL,
	PREMIUMDATE2 DATE NULL,
	CLEARINGACCOUNT VARCHAR2(80) NULL,
	BESTBID NUMBER(38,17) NULL,
	BESTASK NUMBER(38,17) NULL,
	OURLEI VARCHAR2(20) NULL,
	THEIRLEI VARCHAR2(20) NULL,
	BROKERAGEAMOUNT NUMBER(38,17) NULL,
	BROKERAGECURRENCY VARCHAR2(80) NULL,
	REPORTINGPARTY VARCHAR2(80) NULL,
	NAMESPACE VARCHAR2(80) NULL,
	LINKID VARCHAR2(80) NULL,
	TRANSACTIONID2 VARCHAR2(80) NULL,
	TRANSACTIONID3 VARCHAR2(80) NULL,
	TRANSACTIONID4 VARCHAR2(80) NULL,
	TRANSACTIONIDHEDGE1 VARCHAR2(80) NULL,
	TRANSACTIONIDHEDGE2 VARCHAR2(80) NULL,
	TRADEREPOSITORY VARCHAR2(80) NULL,
	MIDPRICE NUMBER(38,17) NULL,
	OURBICCODE VARCHAR2(11) NULL,
	THEIRBICCODE VARCHAR2(11) NULL,
	EXECUTIONFACILITY VARCHAR2(40) NULL,
	MIDMARKETSPOTRATE NUMBER(38,17) NULL,
	MIDMARKETNEARRATE NUMBER(38,17) NULL,
	MIDMARKETFARRATE NUMBER(38,17) NULL,
	MIDMARKETSWAPRATE NUMBER(38,17) NULL,
	BLOCKTRADE NUMBER(3) NULL,
	CLEARINGELIGIBLE NUMBER(3) NULL,
	OURCLEAREXEMP NUMBER(3) NULL,
	THEIRCLEAREXEMP NUMBER(3) NULL,
	WEAREUSPERSON NUMBER(3) NULL,
	THEYAREUSPERSON NUMBER(3) NULL,
	OURREPORTJURISD VARCHAR2(40) NULL,
	THEIRREPORTJURISD VARCHAR2(40) NULL,
	TRANSACTIONIDHEDGE3 VARCHAR2(80) NULL,
	TRANSACTIONIDHEDGE4 VARCHAR2(80) NULL,
	CPUSERID VARCHAR2(40) NULL,
	CPUSERNAME VARCHAR2(40) NULL,
	THEIRCLEARINGACCOUNT VARCHAR2(40) NULL,
	UNIQUEPRODUCTID VARCHAR2(56) NULL,
	UTI1 VARCHAR2(52) NULL,
	UTI2 VARCHAR2(52) NULL,
	PRINTED NUMBER(5) DEFAULT 0 NOT NULL,
	OURNAME VARCHAR2(56) NULL,
	ACCOUNT VARCHAR2(56) NULL,
	OUREMAILADDRESS VARCHAR2(256) NULL,
	THEIREMAILADDRESS VARCHAR2(256) NULL,
	TRADINGINTERFACE VARCHAR2(80) NULL,
	BENCHMARKFIXINGTYPE1 VARCHAR2(20) NULL,
	BENCHMARKFIXINGDATE1 DATE NULL,
	BENCHMARKFIXINGRATE1 VARCHAR2(38) NULL,
	BENCHMARKFIXINGTYPE2 VARCHAR2(20) NULL,
	BENCHMARKFIXINGDATE2 DATE NULL,
	BENCHMARKFIXINGRATE2 VARCHAR2(38) NULL,
	OURJURISDICTION VARCHAR2(280) NULL,
	THEIRJURISDICTION VARCHAR2(280) NULL,
	EXECUTIONVENUETYPE VARCHAR2(280) NULL,
	OURCLEARINGBROKER VARCHAR2(4) NULL,
	OURCLEARINGBROKERLEI VARCHAR2(20) NULL,
	THEIRCLEARINGBROKER VARCHAR2(4) NULL,
	THEIRCLEARINGBROKERLEI VARCHAR2(20) NULL,
	EXECUTIONID VARCHAR2(100) NULL,
	ORDERID VARCHAR2(100) NULL,
	LOCALCODEROLE VARCHAR2(20) NULL,
	ET_MAREF VARCHAR2(50) NULL,
	ET_REPORTINGCENTREID VARCHAR2(50) NULL,
	ET_RISKCCY VARCHAR2(10) NULL,
	ET_CREDITCCY VARCHAR2(3) NULL, 
	ET_TAKERCUSTOM CLOB NULL,
	ET_TICKETTYPE VARCHAR2(38) NULL,
	ET_B2B VARCHAR2(1) NULL,
	ET_MARKUPCOMPLETE VARCHAR2(5) NULL,
	ET_DEALDAY VARCHAR2(20) NULL,
	ET_MAKERLBNID VARCHAR2(30) NULL,
	ET_PROXYGROUPNAME VARCHAR2(100) NULL,
	ET_PROXYGROUPFULLNAME VARCHAR2(100) NULL,
	ET_RISKAMOUNT NUMBER(38,17) NULL,
	ET_NETTYPE VARCHAR2(4) NULL,
	ET_EQUIVCCY VARCHAR2(3) NULL,
	ET_EQUIVPROFITAMOUNT NUMBER(38,17) NULL,
	ET_EQUIVRATE1 NUMBER(38,17) NULL,
	ET_EQUIVRATE1PAIR VARCHAR2(10) NULL,
	ET_EQUIVRATE1BID NUMBER(38,17) NULL,
	ET_EQUIVRATE1ASK NUMBER(38,17) NULL,
	ET_EQUIVRATE2 NUMBER(38,17) NULL,
	ET_EQUIVRATE2PAIR VARCHAR2(10) NULL,
	ET_EQUIVRATE2BID NUMBER(38,17) NULL,
	ET_EQUIVRATE2ASK NUMBER(38,17) NULL,
	ET_CCY2ATTRPARENT VARCHAR2(50) NULL,
	ET_CCY2ATTRVERSIONTYPE VARCHAR2(10) NULL,
	ET_CCY2ATTRVERSIONDISPLAY VARCHAR2(100) NULL,
	ET_REQUIREMENTS1 NUMBER(38,17) NULL,
	ET_REQUIREMENTS2 NUMBER(38,17) NULL,
	ET_BUY1 NUMBER(38,17) NULL,
	ET_BUY2 NUMBER(38,17) NULL,
	ET_SELL1 NUMBER(38,17) NULL,
	ET_SELL2 NUMBER(38,17) NULL,
	ET_RISKAMOUNT1 NUMBER(38,17) NULL,
	ET_RISKAMOUNT2 NUMBER(38,17) NULL,
	ET_CREDITAMOUNT1 NUMBER(38,17) NULL,
	ET_CREDITAMOUNT2 NUMBER(38,17) NULL,
	ET_REFERENCECCYRATE1 NUMBER(38,17) NULL,
	ET_REFERENCECCYRATE2 NUMBER(38,17) NULL,
	ET_EQUIVCCY1 VARCHAR2(3) NULL,
	ET_EQUIVCCY2 VARCHAR2(3) NULL,
	ET_EQUIVPROFITAMOUNT1 NUMBER(38,17) NULL,
	ET_EQUIVPROFITAMOUNT2 NUMBER(38,17) NULL,
	ET_EQUIVAMOUNT1 NUMBER(38,17) NULL,
	ET_EQUIVAMOUNT2 NUMBER(38,17) NULL,
	ET_EQUIVRATE1RATE1 NUMBER(38,17) NULL,
	ET_EQUIVRATE1RATEPAIR1 VARCHAR2(7) NULL,
	ET_EQUIVRATE1RATE2 NUMBER(38,17) NULL,
	ET_EQUIVRATE1RATEPAIR2 VARCHAR2(7) NULL,
	ET_EQUIVRATE1RATE3 NUMBER(38,17) NULL,
	ET_EQUIVRATE1RATEPAIR3 VARCHAR2(7) NULL,
	ET_EQUIVRATE2RATE1 NUMBER(38,17) NULL,
	ET_EQUIVRATE2RATEPAIR1 VARCHAR2(7) NULL,
	ET_EQUIVRATE2RATE2 NUMBER(38,17) NULL,
	ET_EQUIVRATE2RATEPAIR2 VARCHAR2(7) NULL,
	ET_EQUIVRATE2RATE3 NUMBER(38,17) NULL,
	ET_EQUIVRATE2RATEPAIR3 VARCHAR2(7) NULL,
	ET_CROSSCOMPSPOTMARKUPDPS1 NUMBER(38,17) NULL,
	ET_CROSSCOMPSPOTMARKUPDPS2 NUMBER(38,17) NULL,
	ET_INDICATIVEQUOTEALLIN1 NUMBER(38,17) NULL,
	ET_INDICATIVEQUOTEALLIN2 NUMBER(38,17) NULL,
	ET_INDICATIVEQUOTESPOTPRICE1 NUMBER(38,17) NULL,
	ET_INDICATIVEQUOTESPOTPRICE2 NUMBER(38,17) NULL,
	ET_INDICATIVEQUOTEFWDPTS1 NUMBER(38,17) NULL,
	ET_INDICATIVEQUOTEFWDPTS2 NUMBER(38,17) NULL,
	ET_QUOTEALLIN1 NUMBER(38,17) NULL,
	ET_QUOTEALLIN2 NUMBER(38,17) NULL,
	ET_QUOTESPOTPRICE1 NUMBER(38,17) NULL,
	ET_QUOTESPOTPRICE2 NUMBER(38,17) NULL,
	ET_QUOTEFWDPTS1 NUMBER(38,17) NULL,
	ET_QUOTEFWDPTS2 NUMBER(38,17) NULL,
	ET_COREMARKETSPOTPRICE1 NUMBER(38,17) NULL,
	ET_COREMARKETSPOTPRICE2 NUMBER(38,17) NULL,
	ET_MARKETSPOTPRICE1 NUMBER(38,17) NULL,
	ET_MARKETSPOTPRICE2 NUMBER(38,17) NULL,
	ET_CORETAKERSPOTPRICE1 NUMBER(38,17) NULL,
	ET_CORETAKERSPOTPRICE2 NUMBER(38,17) NULL,
	ET_COREMARKETFWDPTS1 NUMBER(38,17) NULL,
	ET_COREMARKETFWDPTS2 NUMBER(38,17) NULL,
	ET_MARKETFWDPTS1 NUMBER(38,17) NULL,
	ET_MARKETFWDPTS2 NUMBER(38,17) NULL,
	ET_SPOTMARKUP1 NUMBER(38,17) NULL,
	ET_SPOTMARKUP2 NUMBER(38,17) NULL,
	ET_FWDMARKUP1 NUMBER(38,17) NULL,
	ET_FWDMARKUP2 NUMBER(38,17) NULL,
	ET_COREMARKETSPOTTIME1 DATE NULL,
	ET_COREMARKETSPOTTIME2 DATE NULL,
	ET_COREMARKETSPOTOFFSETPTS1 NUMBER(38,17) NULL,
	ET_COREMARKETSPOTOFFSETPTS2 NUMBER(38,17) NULL,
	ET_COREMARKETFWDOFFSETPTS1 NUMBER(38,17) NULL,
	ET_COREMARKETFWDOFFSETPTS2 NUMBER(38,17) NULL,
	ET_REQUIREMENTRISKAMOUNT1 NUMBER(38,17) NULL,
	ET_REQUIREMENTRISKAMOUNT2 NUMBER(38,17) NULL,
	ET_REQUIREMENTCREDITAMOUNT1 NUMBER(38,17) NULL,
	ET_REQUIREMENTCREDITAMOUNT2 NUMBER(38,17) NULL,
	TRADINGDATETIME VARCHAR2(27) NULL,
	INSTRUMENTCODETYPE1 VARCHAR2(20) NULL,
	INSTRUMENTCODETYPE2 VARCHAR2(20) NULL,
	INSTRUMENTCODE1 VARCHAR2(12) NULL,
	INSTRUMENTCODE2 VARCHAR2(12) NULL,
	PRICELEG1 NUMBER(38,17) NULL,
	PRICELEG2 NUMBER(38,17) NULL,
	VENUE VARCHAR2(4) NULL,
	QUANTITY1 NUMBER(38,17) NULL,
	QUANTITY2 NUMBER(38,17) NULL,
	NOTIONALAMT1 NUMBER(38,17) NULL,
	NOTIONALAMT2 NUMBER(38,17) NULL,
	TRADINGVENUE1 VARCHAR2(52) NULL,
	TRADINGVENUE2 VARCHAR2(52) NULL,
	BENCFLAG NUMBER(3) DEFAULT -1 NULL,
	NPFTFLAG NUMBER(3) DEFAULT -1 NULL,
	ILQDFLAG NUMBER(3) DEFAULT -1 NULL,
	THRESHOLDFLAG NUMBER(3) DEFAULT -1 NULL,
	EXECUTIONTYPE NUMBER(3) DEFAULT -1 NULL,
	TPACFLAG NUMBER(3) DEFAULT -1 NULL,
	TRANSREF1 VARCHAR2(52) NULL,
	TRANSREF2 VARCHAR2(52) NULL,
	INVESTFIRM NUMBER(3) DEFAULT -1 NULL,
	SUBMITENTITY VARCHAR2(20) NULL,
	BUYER VARCHAR2(20) NULL,
	SELLER VARCHAR2(20) NULL,
	TRANSMISOFORDER NUMBER(3) DEFAULT -1 NULL,
	TRADINGCAPACITY NUMBER(3) DEFAULT -1 NULL,
	COUNTRYOFBRANCH VARCHAR2(2) NULL,
	COMPLEXTRADEID VARCHAR2(35) NULL,
	INSTRUMENTNAME1 VARCHAR2(350) NULL,
	INSTRUMENTNAME2 VARCHAR2(350) NULL,
	STRIKEPRICE1 NUMBER(38,17) NULL,
	STRIKEPRICE2 NUMBER(38,17) NULL,
	WAIVERTHRESHOLD NUMBER(3) DEFAULT -1 NULL,
	WAIVERINSTRTRADEFLAG NUMBER(3) DEFAULT -1 NULL,
	SECFIN NUMBER(3) DEFAULT -1 NULL,
	RESPONSIBLETRADER VARCHAR2(80) NULL,
	RESPONSIBLEEMAIL VARCHAR2(256) NULL,
	RESPONSIBLEALIAS VARCHAR2(40) NULL,
	CALLINITTIME TIMESTAMP NULL,
	ACCEPTTIME TIMESTAMP NULL,
	CONFIRMEDTIME TIMESTAMP NULL,
	EXTRACTEDTIME TIMESTAMP NULL,
	FIRSTENDTIME TIMESTAMP NULL,
	SECONDENDTIME TIMESTAMP NULL,
	QUOTETIME TIMESTAMP NULL,
	QUOTEREJECTTIME TIMESTAMP NULL,
	AGGRESSORINDICATOR NUMBER(3) DEFAULT -1 NULL,
	PREVIOUSLYREPORTED NUMBER(3) NULL,
	DIRECTION3 NUMBER(2) NULL,
	DIRECTION4 NUMBER(2) NULL,
	EXPIRYDATE3 DATE NULL,
	EXPIRYDATE4 DATE NULL,
	STRIKEPRICE3 NUMBER(38,17) NULL,
	STRIKEPRICE4 NUMBER(38,17) NULL,
	EXCHANGERATEPERIOD3 NUMBER(38,17) NULL,
	EXCHANGERATEPERIOD4 NUMBER(38,17) NULL,
	INSTRUMENTCODE3 VARCHAR2(12) NULL,
	INSTRUMENTCODE4 VARCHAR2(12) NULL,
	INSTRUMENTCODETYPE3 VARCHAR2(20) NULL,
	INSTRUMENTCODETYPE4 VARCHAR2(20) NULL,
	INSTRUMENTNAME3 VARCHAR2(350) NULL,
	INSTRUMENTNAME4 VARCHAR2(350) NULL,
	EXPIRYSTYLE2 NUMBER(2) NULL,
	EXPIRYSTYLE3 NUMBER(2) NULL,
	EXPIRYSTYLE4 NUMBER(2) NULL,
	OPTIONTYPE3 VARCHAR2(10) NULL,
	OPTIONTYPE4 VARCHAR2(10) NULL,
	PRICELEG3 NUMBER(38,17) NULL,
	PRICELEG4 NUMBER(38,17) NULL,
	QUANTITY3 NUMBER(38,17) NULL,
	QUANTITY4 NUMBER(38,17) NULL,
	PREMIUMQUOTE3 NUMBER(38,17) NULL,
	PREMIUMQUOTE4 NUMBER(38,17) NULL,
	PREMIUMAMOUNT3 NUMBER(38,17) NULL,
	PREMIUMAMOUNT4 NUMBER(38,17) NULL,
	TRADINGVENUE3 VARCHAR2(52) NULL,
	TRADINGVENUE4 VARCHAR2(52) NULL,
	TRANSREF3 VARCHAR2(52) NULL,
	TRANSREF4 VARCHAR2(52) NULL,
	LASTQTYINCRDECR1 NUMBER(3) DEFAULT -1 NULL,
	LASTQTYINCRDECR2  NUMBER(3) DEFAULT -1 NULL,
	LASTQTYINCRDECR3  NUMBER(3) DEFAULT -1 NULL,
	LASTQTYINCRDECR4  NUMBER(3) DEFAULT -1 NULL,
	BUYER2 VARCHAR2(20) NULL,
	BUYER3 VARCHAR2(20) NULL,
	BUYER4 VARCHAR2(20) NULL,
	SELLER2 VARCHAR2(20) NULL,
	SELLER3 VARCHAR2(20) NULL,
	SELLER4 VARCHAR2(20) NULL,
	INTC1 NUMBER(3) DEFAULT -1 NULL,
	INTC2 NUMBER(3) DEFAULT -1 NULL,
	INTC3 NUMBER(3) DEFAULT -1 NULL,
	INTC4 NUMBER(3) DEFAULT -1 NULL,
	BENCHMARKFIXINGTYPE3 VARCHAR2(20) NULL,
	BENCHMARKFIXINGTYPE4 VARCHAR2(20) NULL,
	BENCHMARKFIXINGDATE3 DATE NULL,
	BENCHMARKFIXINGDATE4 DATE NULL,
	BENCHMARKFIXINGRATE3 VARCHAR2(38) NULL,
	BENCHMARKFIXINGRATE4 VARCHAR2(38) NULL,
	DELIVERYDATE3 DATE NULL,
	DELIVERYDATE4 DATE NULL,
	VOLATILITY3 NUMBER(38,17) NULL,
	VOLATILITY4 NUMBER(38,17) NULL,
	SETTLECURRENCY1 CHAR(3) NULL,
	SETTLECURRENCY2 CHAR(3) NULL,
	SETTLECURRENCY3 CHAR(3) NULL,
	SETTLECURRENCY4 CHAR(3) NULL,
	NOTIONALAMT3 NUMBER(38,17) NULL,
	NOTIONALAMT4 NUMBER(38,17) NULL,
	ET_QUOTESPOTPRICE3 NUMBER(38,17) NULL,
	ET_QUOTESPOTPRICE4 NUMBER(38,17) NULL,
	SWAPPOINTSREFERENCE3 NUMBER(38,17) NULL,
	SWAPPOINTSREFERENCE4 NUMBER(38,17) NULL,
	ET_QUOTEFWDPTS3 NUMBER(38,17) NULL,
	ET_QUOTEFWDPTS4 NUMBER(38,17) NULL,
	DEPOSITRATEREFERENCE3 NUMBER(38,17) NULL,
	DEPOSITRATEREFERENCE4 NUMBER(38,17) NULL,
	DELTA1 NUMBER(38,17) NULL,
	DELTA2 NUMBER(38,17) NULL,
	DELTA3 NUMBER(38,17) NULL,
	DELTA4 NUMBER(38,17) NULL,
	PREMIUMSIDE1 NUMBER(3) DEFAULT -1 NULL,
	PREMIUMSIDE2 NUMBER(3) DEFAULT -1 NULL,
	PREMIUMSIDE3 NUMBER(3) DEFAULT -1 NULL,
	PREMIUMSIDE4 NUMBER(3) DEFAULT -1 NULL,
	PREMIUMQUOTECONVENTION2 NUMBER(2) NULL,
	PREMIUMQUOTECONVENTION3 NUMBER(2) NULL,
	PREMIUMQUOTECONVENTION4 NUMBER(2) NULL,
	TRADINGSTRATEGY2 NUMBER(2) NULL,
	TRADINGSTRATEGY3 NUMBER(2) NULL,
	TRADINGSTRATEGY4 NUMBER(2) NULL,
	RATEDIRECTION2 NUMBER(3) NULL,
	RATEDIRECTION3 NUMBER(3) NULL,
	RATEDIRECTION4 NUMBER(3) NULL,
	PREMIUMDATE3 DATE NULL,
	PREMIUMDATE4 DATE NULL,
	PREMIUMCURRENCY2 VARCHAR2(3) NULL,
	PREMIUMCURRENCY3 VARCHAR2(3) NULL,
	PREMIUMCURRENCY4 VARCHAR2(3) NULL,
	CUTOFF3 VARCHAR2(20) NULL,
	CUTOFF4 VARCHAR2(20) NULL,
	SETTLEMETHOD1 CHAR(1) NULL,
	SETTLEMETHOD2 CHAR(1) NULL,
	SETTLEMETHOD3 CHAR(1) NULL,
	SETTLEMETHOD4 CHAR(1) NULL,
	UNIQUEPRODUCTNAME VARCHAR2(256) NULL,
	OTHERTRADETYPE CHAR(2) NULL,
	UTI3 VARCHAR2(52) NULL,
	UTI4 VARCHAR2(52) NULL,
	STRIKECURRENCY1 CHAR(3) NULL,
	STRIKECURRENCY2 CHAR(3) NULL,
	STRIKECURRENCY3 CHAR(3) NULL,
	STRIKECURRENCY4 CHAR(3) NULL,
	SPOTBASISRATE2 NUMBER(38,17) NULL,
	SPOTBASISRATE3 NUMBER(38,17) NULL,
	SPOTBASISRATE4 NUMBER(38,17) NULL,
	TRADEID VARCHAR2(124) NULL,
	EXECUTIONVENUEID VARCHAR2(20) NULL,
	RAVENUECPTYREFTEXT VARCHAR2(20) NULL,
	RAVENUEREFTEXT VARCHAR2(20) NULL,
	PRODUCT NUMBER(3) NULL,
	SECURITYSUBTYPE VARCHAR2(20) NULL,
	AGREEMENTDESC VARCHAR2(120) NULL,
	AGREEMENTID VARCHAR2(100) NULL,
	AGREEMENTDATE DATE NULL,
	TERMINATIONTYPE NUMBER(3) NULL,
	DELIVERYTYPE NUMBER(3) NULL,
	UNDERLYINGSECURITYID VARCHAR2(100) NULL,
	UNDERLYINGSECURITYIDSOURCE VARCHAR2(20) NULL,
	UNDERLYINGPRODUCT NUMBER(3) NULL,
	UNDERLYINGSECURITYTYPE VARCHAR2(30) NULL,
	UNDERLYINGMATURITYDATE DATE NULL,
	UNDERLYINGISSUER VARCHAR2(100) NULL,
	UNDERLYINGPRICE NUMBER(38,17) NULL,
	UNDERLYINGDIRTYPRICE NUMBER(38,17) NULL,
	UNDERLYINGQTY NUMBER(38,17) NULL,
	UNDERLYINGSTIPTYPE VARCHAR2(40) NULL,
	UNDERLYINGSTIPVALUE VARCHAR2(50) NULL,
	CLEARINGBUSINESSDATE DATE NULL,
	BENCHMARKCURVENAME VARCHAR2(40) NULL,
	BENCHMARKCURVEPOINT VARCHAR2(30) NULL,
	BENCHMARKSECURITYID VARCHAR2(100) NULL,
	BENCHMARKSECURITYIDSOURCE VARCHAR2(20) NULL,
	TERMINATIONDATE DATE NULL,
	ENDINTERESTVOLUME NUMBER(38,17) NULL,
	STARTCASH NUMBER(38,17) NULL,
	ENDCASH NUMBER(38,17) NULL,
	TRADECOLLATERALIZATION NUMBER(3) NULL,
	CLIENTORDERID VARCHAR2(255) NULL,
	STREAMTYPE1 NUMBER(3) NULL, 
	STREAMTYPE2 NUMBER(3) NULL, 
	INDEXCURVEUNIT1 VARCHAR2(2) NULL, 
	INDEXCURVEUNIT2 VARCHAR2(2) NULL,
	INDEXCURVEPERIOD1 NUMBER(3) NULL, 
	INDEXCURVEPERIOD2 NUMBER(3) NULL,  
	EFFECTIVEDATE DATE NULL,
	EFFECTIVEBUSINESSDAYCONVENTION NUMBER(3) NULL, 
	TERMINATIONBUSINESSDAYCONVENTION NUMBER(3) NULL, 
	PAYMENTFREQUENCYPERIOD1 NUMBER(3) NULL, 
	PAYMENTFREQUENCYPERIOD2 NUMBER(3) NULL, 
	PAYMENTFREQUENCYUNIT1 VARCHAR2(2) NULL, 
	PAYMENTFREQUENCYUNIT2 VARCHAR2(2) NULL,
	PAYMENTBUSINESSDAYCONVENTION1 NUMBER(3) NULL,
	PAYMENTBUSINESSDAYCONVENTION2 NUMBER(3) NULL,
	RESETCALENDAR2 VARCHAR2(20) NULL,
	RESETFREQUENCYPERIOD1 NUMBER(3) NULL, 
	RESETFREQUENCYPERIOD2 NUMBER(3) NULL, 
	RESETFREQUENCYUNIT1 VARCHAR2(2) NULL, 
	RESETFREQUENCYUNIT2 VARCHAR2(2) NULL, 
	RESETBUSINESSDAYCONVENTION1 NUMBER(3) NULL,
	RESETBUSINESSDAYCONVENTION2 NUMBER(3) NULL,
	ISSUEDATE DATE NULL,
	SECURITYALTID VARCHAR2(100) NULL, 
	SECURITYALTIDSOURCE NUMBER(3) NULL, 
	ACCRUEDDAYS NUMBER(10) NULL,
	LEGCURRENCY1 VARCHAR2(3) NULL,
	LEGCURRENCY2 VARCHAR2(3) NULL,
	LEGCURRENCY3 VARCHAR2(3) NULL,
	LEGCURRENCY4 VARCHAR2(3) NULL,
	CONSTRAINT UN_TICKETS UNIQUE (DEALID, LOCALTCID, SOURCEREFERENCE, TIMEOFDEAL, SCOPE)
) TABLESPACE DT_ARCHIVE8N;


CREATE INDEX C##RTR_DT8N.TICKETS_CCY1 ON C##RTR_DT8N.TICKETS(CURRENCY1) TABLESPACE INDEX_SPACE8N;
CREATE INDEX C##RTR_DT8N.TICKETS_CCY2 ON C##RTR_DT8N.TICKETS(CURRENCY2) TABLESPACE INDEX_SPACE8N;
CREATE INDEX C##RTR_DT8N.TICKETS_DEALER ON C##RTR_DT8N.TICKETS(DEALERID) TABLESPACE INDEX_SPACE8N;
CREATE INDEX C##RTR_DT8N.TICKETS_DEALID ON C##RTR_DT8N.TICKETS(DEALID) TABLESPACE INDEX_SPACE8N;
CREATE INDEX C##RTR_DT8N.TICKETS_DTYPE ON C##RTR_DT8N.TICKETS(PUREDEALTYPE, DEALTYPE) TABLESPACE INDEX_SPACE8N;
CREATE INDEX C##RTR_DT8N.TICKETS_LOGON ON C##RTR_DT8N.TICKETS(LOCALTCID, DEALERID, DEALERNAME) TABLESPACE INDEX_SPACE8N;
CREATE INDEX C##RTR_DT8N.TICKETS_PROCESSED ON C##RTR_DT8N.TICKETS(PROCESSED) TABLESPACE INDEX_SPACE8N;
CREATE INDEX C##RTR_DT8N.TICKETS_RRN ON C##RTR_DT8N.TICKETS(REVIEWREFERENCENUMBER) TABLESPACE INDEX_SPACE8N;
CREATE INDEX C##RTR_DT8N.TICKETS_SR ON C##RTR_DT8N.TICKETS(SOURCEREFERENCE) TABLESPACE INDEX_SPACE8N;
CREATE INDEX C##RTR_DT8N.TICKETS_TCID ON C##RTR_DT8N.TICKETS(BANK1DEALINGCODE) TABLESPACE INDEX_SPACE8N;
CREATE INDEX C##RTR_DT8N.TICKETS_TOD ON C##RTR_DT8N.TICKETS(TIMEOFDEAL) TABLESPACE INDEX_SPACE8N;
CREATE INDEX C##RTR_DT8N.TICKETS_DEALERNAME ON C##RTR_DT8N.TICKETS(DEALERNAME) TABLESPACE INDEX_SPACE8N;
CREATE INDEX C##RTR_DT8N.TICKETS_COVERIDX1 ON C##RTR_DT8N.TICKETS(LOCALTCID, DEALERID, DEALERNAME, SOURCEREFERENCE, TIMEOFDEAL) TABLESPACE INDEX_SPACE8N;
CREATE INDEX C##RTR_DT8N.TICKETS_COVERIDX2 ON C##RTR_DT8N.TICKETS(TIMEOFDEAL, LOCALTCID, SOURCEREFERENCE, PUREDEALTYPE, BANK1DEALINGCODE, CURRENCY1, DEALVOLUMECURRENCY1, BANK1NAME) TABLESPACE INDEX_SPACE8N;
CREATE INDEX C##RTR_DT8N.TICKETS_COVERIDX3 ON C##RTR_DT8N.TICKETS(TIMEOFDEAL, CURRENCY1, LOCALTCID, PUREDEALTYPE, CURRENCY2, DEALVOLUMECURRENCY1) TABLESPACE INDEX_SPACE8N;
CREATE INDEX C##RTR_DT8N.TICKETS_COVERIDX4 ON C##RTR_DT8N.TICKETS(TIMEOFDEAL, LOCALTCID, SOURCEREFERENCE, BANK1DEALINGCODE, BANK1NAME) TABLESPACE INDEX_SPACE8N;
CREATE INDEX C##RTR_DT8N.TICKETS_COVERIDX5 ON C##RTR_DT8N.TICKETS(LOCALTCID, SOURCEREFERENCE, TIMEOFDEAL, DEALID, PROCESSED, PROCESSEDBY, SOURCEOFDATA) TABLESPACE INDEX_SPACE8N;


CREATE TABLE C##RTR_DT8N.CALLS(
	CALLTIME DATE NOT NULL,
	CALLNUMBER NUMBER(10) NOT NULL,
	CALLERTCID CHAR(4) NULL,
	LOCALTCID CHAR(4) NULL,
	DEALERFLAG CHAR(2) NULL,
	CALLLETTER CHAR(1) NULL,
	CALLDELAY NUMBER(5) NULL,
	WITHDRAWNREASON NUMBER(3) NULL,
	DEALERID VARCHAR2(40) NULL,
	INTERESTMESSAGE CHAR(14) NULL,
	INTERESTDATECHECKSUM NUMBER(10) DEFAULT 0 NULL, 
	CONSTRAINT UN_CALLS UNIQUE (CALLLETTER, CALLNUMBER, INTERESTDATECHECKSUM, LOCALTCID) 
) TABLESPACE DT_ARCHIVE8N;

CREATE INDEX C##RTR_DT8N.CIDX_CALLTIME ON C##RTR_DT8N.CALLS(CALLTIME) TABLESPACE INDEX_SPACE8N;



CREATE TABLE C##RTR_DT8N.COUNTERPARTIES(
	LOCALTCID VARCHAR2(4) NULL,
	NAME VARCHAR2(255) NULL,
	CITY VARCHAR2(20) NULL,
	STATUS VARCHAR2(5) NULL,
	ANSWERBACK VARCHAR2(50) NULL,
	COUNTRY VARCHAR2(20) NULL,
	NOTES VARCHAR2(500) NULL  
) TABLESPACE DT_ARCHIVE8N;
CREATE UNIQUE INDEX C##RTR_DT8N.Counterparties_TCID ON C##RTR_DT8N.Counterparties(LOCALTCID) TABLESPACE INDEX_SPACE8N;



CREATE TABLE C##RTR_DT8N.USERS(
	USERID VARCHAR2(255) NULL,
	USERNAME VARCHAR2(30) NULL,
	PERMISSIONS NUMBER(10,0) NULL,
	TRADESPERPAGE NUMBER(5,0) NULL,
	AUTOREFRESH NUMBER(5,0) NULL,
	FONTSIZE NUMBER(5,0) NULL,
	TOOLBAR NUMBER(5,0) NULL,
	REFRESHDELAY NUMBER(5,0) NULL,
	LOCALTCIDSELECTION CLOB NULL,
	LOCALTCIDFILTER CLOB NULL,
	REPORTPERIOD NUMBER(5,0) NULL,
	ANALYSISPERIOD NUMBER(5,0) NULL,
	LASTMODIFIED DATE NULL,
	ORDERFIELD1 VARCHAR2(30) NULL,
	ORDERFIELD2 VARCHAR2(30) NULL,
	ORDERFIELD3 VARCHAR2(30) NULL,
	ORDER1ASC NUMBER(5,0) NULL,
	ORDER2ASC NUMBER(5,0) NULL,
	ORDER3ASC NUMBER(5,0) NULL,
	CONVERTGMT NUMBER(5,0) NULL,
	DEALASGMT NUMBER(5,0) NULL,
	SEARCHPERIOD NUMBER(5) NULL,
	ROLE NUMBER(3,0) DEFAULT 5 NULL,
	DATEINPUTFORMAT NUMBER(3,0) DEFAULT 0 NULL,
	LOCALTCIDFILTERTOPRECENT CLOB NULL,
	HOMEPAGELAYOUT	NUMBER(10,0) NULL,
	TimeOption NUMBER(3,0) DEFAULT 0 NULL,
	HOMEPAGELISTING NUMBER(3,0) DEFAULT 0 NULL,
	HOMEPAGEPERIOD NUMBER(5,0) DEFAULT 0 NULL,
	HOMEPAGETRADESPERPAGE NUMBER(5,0) DEFAULT 20 NULL,
	ENABLECOMPACTPRINTOUT NUMBER(3) DEFAULT 0 NOT NULL,
	ENABLEUSER NUMBER(3) DEFAULT 0 NOT NULL,
	ENABLELICENSEEXPIREALERT NUMBER(3) DEFAULT 1 NOT NULL
) TABLESPACE DT_ARCHIVE8N;
CREATE UNIQUE INDEX C##RTR_DT8N.USERS_ID ON C##RTR_DT8N.USERS(USERID) TABLESPACE INDEX_SPACE8N;
ALTER TABLE C##RTR_DT8N.USERS ADD CONSTRAINT PK_USERID PRIMARY KEY (USERID);



CREATE TABLE C##RTR_DT8N.REPORTS(
	DESCRIPTION VARCHAR2(60) NULL,
	REPFILE VARCHAR2(50) NULL,
	CUSTOMREPORTID NUMBER(10,0) NULL,
	CHOSEN NUMBER(1,0) NOT NULL
) TABLESPACE DT_ARCHIVE8N;
CREATE UNIQUE INDEX C##RTR_DT8N.Reports_Id ON C##RTR_DT8N.Reports(CUSTOMREPORTID) TABLESPACE INDEX_SPACE8N;



CREATE TABLE C##RTR_DT8N.VERSION(
	MAJORREVISION NUMBER(5,0) NOT NULL,
	MEDIUMREVISION NUMBER(5,0) NOT NULL,
	MINORREVISION NUMBER(5,0) NOT NULL,
	RELEASEDATE DATE NOT NULL,
	PRODUCTNAME VARCHAR2(255) NULL
) TABLESPACE DT_ARCHIVE8N;



CREATE TABLE C##RTR_DT8N.TBUSERAUDIT(
    EDITORUSERLOGON VARCHAR2(255) NOT NULL,
    EDITRECORDUSERLOGONBEFORE VARCHAR2(255) NULL,
    EDITRECORDUSERNAMEBEFORE VARCHAR2(255) NULL,
    EDITRECORDUSERLOGONAFTER VARCHAR2(255) NULL,
    EDITRECORDUSERNAMEAFTER VARCHAR2(255) NULL,
    PERMISSIONBEFORE NUMBER(10,0) NULL,
    PERMISSIONAFTER NUMBER(10,0) NULL,
    EDITTIMESTAMP DATE DEFAULT SYSDATE NOT NULL,
    ADMINACTION VARCHAR2(20) NULL,
    TCIDFILTERBEFORE VARCHAR2(255) NULL,
    TCIDFILTERAFTER VARCHAR2(255) NULL
) TABLESPACE DT_ARCHIVE8N;



CREATE TABLE C##RTR_DT8N.TBRUNNINGNUMBER(
	KEYNAME VARCHAR2(50) NOT NULL,
	RUNNINGVALUE NUMBER(18, 0) NOT NULL,
	MINVALUE NUMBER(18, 0) NOT NULL,
	MAXVALUE NUMBER(18, 0) NOT NULL,
	CONSTRAINT UN_TBRUNNINGNUMBER UNIQUE (KEYNAME) 
) TABLESPACE DT_ARCHIVE8N;
INSERT INTO C##RTR_DT8N.TBRUNNINGNUMBER(KEYNAME,RUNNINGVALUE,MINVALUE,MAXVALUE) VALUES ('AutoTicketDealID',1,1,999999);
INSERT INTO C##RTR_DT8N.TBRUNNINGNUMBER(KEYNAME,RUNNINGVALUE,MINVALUE,MAXVALUE) VALUES ('ManualTicketDealID',1,1,999999);



CREATE TABLE C##RTR_DT8N.TBAUTOTICKETSGENERATIONTCIDS(
    LOCALTCID CHAR(4) NOT NULL
) TABLESPACE DT_ARCHIVE8N;
ALTER TABLE C##RTR_DT8N.TBAUTOTICKETSGENERATIONTCIDS ADD CONSTRAINT PK_TBAUTOTICKETSTCIDS PRIMARY KEY (LOCALTCID);



CREATE TABLE C##RTR_DT8N.TBAUTOCHECKNODEALTCIDS(
    LOCALTCID CHAR(4) NOT NULL
) TABLESPACE DT_ARCHIVE8N;
ALTER TABLE C##RTR_DT8N.TBAUTOCHECKNODEALTCIDS ADD CONSTRAINT PK_TBAUTOCHECKNODEALTCIDS PRIMARY KEY (LOCALTCID);



CREATE TABLE C##RTR_DT8N.TBLOGINLOG(
    USERID VARCHAR2(255) NULL,
	DATETIME DATE DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
	STATUS NUMBER(3,0) DEFAULT 0  NOT NULL
) TABLESPACE DT_ARCHIVE8N;
CREATE INDEX C##RTR_DT8N.TBLOGINLOG_DATETIME ON C##RTR_DT8N.TBLOGINLOG(DATETIME) TABLESPACE INDEX_SPACE8N;



CREATE TABLE C##RTR_DT8N.TBTRADELOG(
    USERID VARCHAR2(255) NULL,
    USERNAME VARCHAR2(30) NULL,
	ACCESSDATETIME DATE DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
	PARENTMENUNAME VARCHAR2(255) NULL,
	CURRENTMENUNAME VARCHAR2(255) NULL,
	LOGTYPE NUMBER(3,0) NULL,
	TICKETID ROWID NULL,
	TICKETNO VARCHAR2(20) NULL,
	CONVID ROWID NULL,
	CONVNO VARCHAR2(20) NULL
) TABLESPACE DT_ARCHIVE8N;
CREATE INDEX C##RTR_DT8N.TBTRADELOG_ACCESSDATETIME ON C##RTR_DT8N.TBTRADELOG(ACCESSDATETIME) TABLESPACE INDEX_SPACE8N;



CREATE TABLE C##RTR_DT8N.TBADMINLOG(
    USERID VARCHAR2(255) NOT NULL,
	DATETIME DATE DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
	ACTION NUMBER(3,0) NULL,
	SECTION VARCHAR2(50) NULL,
	OLDVALUE CLOB NULL,
	NEWVALUE CLOB NULL
) TABLESPACE DT_ARCHIVE8N;
CREATE INDEX C##RTR_DT8N.TBADMINLOG_DATETIME ON C##RTR_DT8N.TBADMINLOG(DATETIME) TABLESPACE INDEX_SPACE8N;



--tbSystemConfiguration
CREATE TABLE C##RTR_DT8N.TBSYSTEMCONFIGURATION(
    AUDITTRAILLOGENABLE NUMBER(3,0) DEFAULT 0 NULL,
	AUDITTRAILLOGOVERWRITEDAYS NUMBER(5,0) DEFAULT 30 NULL,
	AUDITTRAILLOGJOBTIME VARCHAR2(10)  NULL,
	AUDITTRAILLOGDAYOFWEEK VARCHAR2(30) NULL,
	ATG_CURRENTCONFIRMTEXT VARCHAR2(500) NULL,
	ATG_CURRENTNONSTDTEXT VARCHAR2(500) NULL,
	ATG_SQLSTATEMENT CLOB NULL,
	ATG_CHECK1 NUMBER(3) NULL,
	ATG_CHECK2 NUMBER(3) NULL
) TABLESPACE DT_ARCHIVE8N;

SET DEFINE OFF;
INSERT INTO C##RTR_DT8N.TBSYSTEMCONFIGURATION (
	AUDITTRAILLOGENABLE
	,AUDITTRAILLOGOVERWRITEDAYS
	,AUDITTRAILLOGJOBTIME
	,AUDITTRAILLOGDAYOFWEEK
	,ATG_CURRENTCONFIRMTEXT
	,ATG_CURRENTNONSTDTEXT
	,ATG_SQLSTATEMENT,ATG_CHECK1,ATG_CHECK2
) VALUES(
	0
	,30
	,'00:00'
	,'SUN'
	,'"THANKS AND BYE" ~ "THX BI" ~ "ALL AGREED" ~ "TKS FOR THE DEAL"'
	,'"FIXED INCOME"'
	,NULL
	,0
	,0);
SET DEFINE ON;



--tbSourceOfData
CREATE TABLE C##RTR_DT8N.tbSourceOfData(
	Code NUMBER(3,0),
	SOURCE VARCHAR2(50),
	APPLYBROKERNAME NUMBER(3) NULL
 )TABLESPACE DT_ARCHIVE8N;
ALTER TABLE C##RTR_DT8N.tbSourceOfData ADD CONSTRAINT PK_tbSourceOfData PRIMARY KEY (Code);

INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (1,'Offline');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (2,'Matching');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (3,'Dealing');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (4,'EBS');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (5,'Manual');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (6,'DDN');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (8,'ICAP-E');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (9,'ICAP-V');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (10,'RTF-CME');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (11,'3rd Party');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (12,'RTFX');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (17,'FXMS');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (18,'FXMS Clearing');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (21,'DB AutoBahn');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (30,'RP Martin');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (31,'BGC eSpeed');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (32,'Meitan');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (36,'Tradition');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (38,'Bierbaums');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (39,'DirectFX');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (43,'Tullet Prebon');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (45,'Carl Kliem');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (51,'Citibank');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (61,'Conticap');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (66,'Electronic Trading');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (73,'Electronic Trading');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (77,'Electronic Trading');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (80,'BARX');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (81,'3rd Party');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (82,'ET');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (83,'Refinitiv Dealing Aggregator');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (84,'Adv Dealing');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (90,'FXall POMS');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (91,'FXall Order Book');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (92,'FXall Bankstream');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (93,'FXall Treasury Center');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (98,'MM Callouts');
INSERT INTO C##RTR_DT8N.tbSourceOfData(Code,Source) VALUES (99,'Auctions');



CREATE TABLE C##RTR_DT8N.TBPUREDEALTYPE(
	CODE NUMBER(10,0),
	DEALTYPE VARCHAR2(50)
 )TABLESPACE DT_ARCHIVE8N;
ALTER TABLE C##RTR_DT8N.TBPUREDEALTYPE ADD CONSTRAINT PK_TBPUREDEALTYPE PRIMARY KEY (CODE);

INSERT INTO C##RTR_DT8N.TBPUREDEALTYPE(CODE,DEALTYPE) VALUES (2,'Spot');
INSERT INTO C##RTR_DT8N.TBPUREDEALTYPE(CODE,DEALTYPE) VALUES (4,'Outright');
INSERT INTO C##RTR_DT8N.TBPUREDEALTYPE(CODE,DEALTYPE) VALUES (7,'FXO');
INSERT INTO C##RTR_DT8N.TBPUREDEALTYPE(CODE,DEALTYPE) VALUES (8,'Swap');
INSERT INTO C##RTR_DT8N.TBPUREDEALTYPE(CODE,DEALTYPE) VALUES (9,'OIS');
INSERT INTO C##RTR_DT8N.TBPUREDEALTYPE(CODE,DEALTYPE) VALUES (10,'IRS');
INSERT INTO C##RTR_DT8N.TBPUREDEALTYPE(CODE,DEALTYPE) VALUES (13,'Repo');
INSERT INTO C##RTR_DT8N.TBPUREDEALTYPE(CODE,DEALTYPE) VALUES (14,'FI');
INSERT INTO C##RTR_DT8N.TBPUREDEALTYPE(CODE,DEALTYPE) VALUES (16,'Deposit');
INSERT INTO C##RTR_DT8N.TBPUREDEALTYPE(CODE,DEALTYPE) VALUES (18,'Netting');
INSERT INTO C##RTR_DT8N.TBPUREDEALTYPE(CODE,DEALTYPE) VALUES (21,'Banknote');
INSERT INTO C##RTR_DT8N.TBPUREDEALTYPE(CODE,DEALTYPE) VALUES (32,'FRA');
INSERT INTO C##RTR_DT8N.TBPUREDEALTYPE(CODE,DEALTYPE) VALUES (64,'Bullion');
INSERT INTO C##RTR_DT8N.TBPUREDEALTYPE(CODE,DEALTYPE) VALUES (128,'Outright');
INSERT INTO C##RTR_DT8N.TBPUREDEALTYPE(CODE,DEALTYPE) VALUES (32000,'Other');



CREATE TABLE C##RTR_DT8N.TBDEALTYPE(
	CODE NUMBER(3,0),
	DIRECTION VARCHAR2(50),
	DIRECTIONLIST VARCHAR2(50)
)TABLESPACE DT_ARCHIVE8N;
ALTER TABLE C##RTR_DT8N.TBDEALTYPE ADD CONSTRAINT PK_TBDEALTYPE PRIMARY KEY (CODE);

INSERT INTO C##RTR_DT8N.TBDEALTYPE(CODE,DIRECTION,DIRECTIONLIST) VALUES (1,'Buy','Buy');
INSERT INTO C##RTR_DT8N.TBDEALTYPE(CODE,DIRECTION,DIRECTIONLIST) VALUES (2,'Sell','Sell');
INSERT INTO C##RTR_DT8N.TBDEALTYPE(CODE,DIRECTION,DIRECTIONLIST) VALUES (3,'Buy ' || chr(38) || ' Sell','Buy ' || chr(38) || ' Sell');
INSERT INTO C##RTR_DT8N.TBDEALTYPE(CODE,DIRECTION,DIRECTIONLIST) VALUES (4,'Sell ' || chr(38) || ' Buy','Sell ' || chr(38) || ' Buy');
INSERT INTO C##RTR_DT8N.TBDEALTYPE(CODE,DIRECTION,DIRECTIONLIST) VALUES (5,'Lend','Lend (Deposit)');
INSERT INTO C##RTR_DT8N.TBDEALTYPE(CODE,DIRECTION,DIRECTIONLIST) VALUES (6,'Borrow','Borrow (Deposit)');
INSERT INTO C##RTR_DT8N.TBDEALTYPE(CODE,DIRECTION,DIRECTIONLIST) VALUES (7,'Lend','Lend (FRA)');
INSERT INTO C##RTR_DT8N.TBDEALTYPE(CODE,DIRECTION,DIRECTIONLIST) VALUES (8,'Borrow','Borrow (FRA)');
INSERT INTO C##RTR_DT8N.TBDEALTYPE(CODE,DIRECTION,DIRECTIONLIST) VALUES (9,'Receive','Receive');
INSERT INTO C##RTR_DT8N.TBDEALTYPE(CODE,DIRECTION,DIRECTIONLIST) VALUES (10,'Pay','Pay');



CREATE TABLE C##RTR_DT8N.VERSIONTHIRDPARTY(
	PRODUCTNAME VARCHAR2(255) NOT NULL,
	VERSION VARCHAR2(30) NOT NULL,
	RELEASEDDATE DATE NOT NULL,
	CREATEDDATE DATE DEFAULT SYSDATE NOT NULL,
	CONSTRAINT UN_VERSIONTHIRDPARTY UNIQUE (PRODUCTNAME, VERSION)
)TABLESPACE DT_ARCHIVE8N;



CREATE TABLE C##RTR_DT8N.TBCLEARINGHOUSE(
	CLEARERNUMBER NUMBER(10,0) NOT NULL,
	CLEARERFULLNAME VARCHAR2(50) NOT NULL
 )TABLESPACE DT_ARCHIVE8N;
ALTER TABLE C##RTR_DT8N.TBCLEARINGHOUSE ADD CONSTRAINT PK_TBCLEARINGHOUSE PRIMARY KEY (CLEARERNUMBER);



CREATE TABLE C##RTR_DT8N.TBUSERCUSTOMIZEVIEW(
	USERID VARCHAR2(255) NOT NULL,
	CALLERID VARCHAR2(50) NOT NULL,
	GRIDVIEWTYPE VARCHAR2(50) NOT NULL,
	USEDEFAULTVIEW NUMBER(1) DEFAULT 1 NULL,
	CUSTOMIZEVIEWCOLUMN CLOB NULL,
	USEDEFAULTSORTING NUMBER(1) DEFAULT 1 NULL,
	ORDERFIELD1 VARCHAR2(5) NULL,
	ORDER1ASC	NUMBER(1) DEFAULT 1 NULL,
	ORDERFIELD2 VARCHAR2(5) NULL,
	ORDER2ASC	NUMBER(1) DEFAULT 1 NULL,
	ORDERFIELD3 VARCHAR2(5) NULL,
	ORDER3ASC	NUMBER(1) DEFAULT 1 NULL,
	CONSTRAINT UN_TBUSERCUSTOMIZEVIEW UNIQUE (USERID, CALLERID, GRIDVIEWTYPE)
 ) TABLESPACE DT_ARCHIVE8N;

 
 
CREATE TABLE C##RTR_DT8N.TBROLES(
	ROLE NUMBER(10,0) NOT NULL,
	ROLENAME VARCHAR2(50) NOT NULL,
	PERMISSIONS NUMBER(10,0) DEFAULT 0 NOT NULL,
	HOMEPAGELAYOUT	NUMBER(10,0) NULL,
	DEFAULTROLE	NUMBER(10,0) DEFAULT 0 NOT NULL,
	CONSTRAINT UN_TBROLES UNIQUE (ROLE)
 ) TABLESPACE DT_ARCHIVE8N;

INSERT INTO C##RTR_DT8N.TBROLES(ROLE, ROLENAME, PERMISSIONS, HOMEPAGELAYOUT) VALUES (0, 'Administrator', 32734, 511);
INSERT INTO C##RTR_DT8N.TBROLES(ROLE, ROLENAME) VALUES (1, 'BO Manager');
INSERT INTO C##RTR_DT8N.TBROLES(ROLE, ROLENAME) VALUES (2, 'eTrader');
INSERT INTO C##RTR_DT8N.TBROLES(ROLE, ROLENAME) VALUES (3, 'MO Manager');
INSERT INTO C##RTR_DT8N.TBROLES(ROLE, ROLENAME) VALUES (4, 'Trader');
INSERT INTO C##RTR_DT8N.TBROLES(ROLE, ROLENAME, PERMISSIONS, HOMEPAGELAYOUT, DEFAULTROLE) VALUES (5, 'User', 80, 387, 1);
INSERT INTO C##RTR_DT8N.TBROLES(ROLE, ROLENAME) VALUES (255, 'Unknown');



--tbCustomDealingFields
CREATE TABLE C##RTR_DT8N.TBCUSTOMDEALINGFIELDS (
    CUSTOMFIELDNUMBER NUMBER       NOT NULL,
    CUSTOMFIELDNAME   VARCHAR2(50)     NULL,
    CONSTRAINT PK_CUSTOMFIELDNUMBER
    PRIMARY KEY (CUSTOMFIELDNUMBER)
        USING INDEX PCTFREE 10
                    INITRANS 2
                    MAXTRANS 255
                    TABLESPACE DT_ARCHIVE8N
                    STORAGE(INITIAL 40K
                           NEXT 40K
                           MINEXTENTS 1
                           MAXEXTENTS 505
                           PCTINCREASE 50
                           FREELISTS 1
                           FREELIST GROUPS 1
                           BUFFER_POOL DEFAULT)
	NOLOGGING,
	CONSTRAINT UCONST_CUSTOMFIELDNUMBER CHECK (CUSTOMFIELDNUMBER > 0 AND CUSTOMFIELDNUMBER < 7)
) TABLESPACE DT_ARCHIVE8N;



CREATE TABLE C##RTR_DT8N.TBCHECKTICKETSTCIDS(
    LOCALTCID CHAR(4) NOT NULL
) TABLESPACE DT_ARCHIVE8N;



CREATE TABLE C##RTR_DT8N.TBUSERTCIDDEALEREXCEPTIONLIST(
    USERID_FK VARCHAR2(255) NOT NULL,
    LOCALTCID CHAR(4) NOT NULL,
    DEALERID VARCHAR2(40) NOT NULL
) TABLESPACE DT_ARCHIVE8N;
ALTER TABLE C##RTR_DT8N.TBUSERTCIDDEALEREXCEPTIONLIST ADD CONSTRAINT PK_TBUSRTCIDDEALEREXCEPTION PRIMARY KEY (USERID_FK, LOCALTCID, DEALERID)
USING INDEX TABLESPACE DT_ARCHIVE8N;



CREATE TABLE C##RTR_DT8N.TBSEARCH(
	SEARCHID NUMBER(18,0) NOT NULL,
	USERID VARCHAR2(255) NULL,
	SEARCHNAME VARCHAR2(50) NULL,
	SEARCHDESCRIPTION VARCHAR2(100) NULL,
	CREATEDDATE DATE DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
	SEARCHDEFAULT NUMBER(3) NULL,
	SEARCHSCOPE NUMBER(3) DEFAULT 0 NULL,
	SEARCHHOMEPAGEENABLE NUMBER(3) DEFAULT 0 NULL,
	SEARCHSYSTEMROLE NUMBER(3) NULL,
	SEARCHSYSTEMENABLE NUMBER(3) DEFAULT 0 NULL
) TABLESPACE DT_ARCHIVE8N;
ALTER TABLE C##RTR_DT8N.TBSEARCH ADD CONSTRAINT PK_TBSEARCH PRIMARY KEY (SEARCHID);



CREATE TABLE C##RTR_DT8N.TBSEARCHFIELD(
	ID NUMBER(18,0) NOT NULL,
	FIELDID VARCHAR2(50) NULL,
	FIELDVALUE NVARCHAR2(2000) NULL,
	FIELDPOSITION NUMBER(5) NULL,
	SEARCHID NUMBER(18,0) NULL
) TABLESPACE DT_ARCHIVE8N;
ALTER TABLE C##RTR_DT8N.TBSEARCHFIELD ADD CONSTRAINT PK_TBSEARCHFIELD PRIMARY KEY (ID);



CREATE TABLE C##RTR_DT8N.TBMYLINKSPERSONALIZATION(
	WEBPARTID Number(3,0) NOT NULL,
	USERID VARCHAR2(255) NOT NULL,
	ZONEID Number(3,0) NOT NULL,
	ZONEINDEX Number(3,0) NOT NULL
) TABLESPACE DT_ARCHIVE8N;
ALTER TABLE C##RTR_DT8N.TBMYLINKSPERSONALIZATION ADD CONSTRAINT PK_TBMYLINKSPERSONALIZATION PRIMARY KEY (WEBPARTID, USERID);



CREATE TABLE C##RTR_DT8N.TBUSERDEFINED
(
	DEALID CHAR(15) NOT NULL,
	TIMEOFDEAL DATE NOT NULL,
	SOURCEREFERENCE char(11) NOT NULL,
	USERDEFINEDTITLE4 VARCHAR2(20) NULL,
	USERDEFINEDVALUE4 NVARCHAR2(40) NULL,
	USERDEFINEDTITLE5 VARCHAR2(20) NULL,
	USERDEFINEDVALUE5 NVARCHAR2(40) NULL,
	USERDEFINEDTITLE6 VARCHAR2(20) NULL,
	USERDEFINEDVALUE6 NVARCHAR2(40) NULL,
	USERDEFINEDTITLE7 VARCHAR2(20) NULL,
	USERDEFINEDVALUE7 NVARCHAR2(40) NULL,
	USERDEFINEDTITLE8 VARCHAR2(20) NULL,
	USERDEFINEDVALUE8 NVARCHAR2(40) NULL,
	USERDEFINEDTITLE9 VARCHAR2(20) NULL,
	USERDEFINEDVALUE9 NVARCHAR2(40) NULL,
	USERDEFINEDTITLE10 VARCHAR2(20) NULL,
	USERDEFINEDVALUE10 NVARCHAR2(40) NULL,	
	USERDEFINEDTITLE11 VARCHAR2(20) NULL,
	USERDEFINEDVALUE11 NVARCHAR2(40) NULL,
	USERDEFINEDTITLE12 VARCHAR2(20) NULL,
	USERDEFINEDVALUE12 NVARCHAR2(40) NULL,	
	USERDEFINEDTITLE13 VARCHAR2(20) NULL,
	USERDEFINEDVALUE13 NVARCHAR2(40) NULL,
	USERDEFINEDTITLE14 VARCHAR2(20) NULL,
	USERDEFINEDVALUE14 NVARCHAR2(40) NULL,
	USERDEFINEDTITLE15 VARCHAR2(20) NULL,
	USERDEFINEDVALUE15 NVARCHAR2(40) NULL,
	USERDEFINEDTITLE16 VARCHAR2(20) NULL,
	USERDEFINEDVALUE16 NVARCHAR2(40) NULL,
	USERDEFINEDTITLE17 VARCHAR2(20) NULL,
	USERDEFINEDVALUE17 NVARCHAR2(40) NULL,
	USERDEFINEDTITLE18 VARCHAR2(20) NULL,
	USERDEFINEDVALUE18 NVARCHAR2(40) NULL,
	USERDEFINEDTITLE19 VARCHAR2(20) NULL,
	USERDEFINEDVALUE19 NVARCHAR2(40) NULL,
	USERDEFINEDTITLE20 VARCHAR2(20) NULL,
	USERDEFINEDVALUE20 NVARCHAR2(40) NULL,		
  CONSTRAINT TBUSERDEFINED_PK PRIMARY KEY(DEALID,TIMEOFDEAL,SOURCEREFERENCE)
) TABLESPACE DT_ARCHIVE8N;


CREATE TABLE C##RTR_DT8N.ALLOCATIONS(
	DEALID CHAR(15) NULL,
	LOCALTCID CHAR(4) NULL,
	SOURCEREFERENCE CHAR(11) NOT NULL,
	TIMEOFDEAL DATE NOT NULL,
	ORDERID VARCHAR2(100 BYTE) NOT NULL,
	ALLOCATIONID VARCHAR2(30 BYTE) NOT NULL, 
	ACCOUNT VARCHAR2(38 BYTE) NULL, 
	DEALTAMOUNT VARCHAR2(38 BYTE) NULL, 
	DEALTCURRENCY CHAR(3 BYTE) NULL, 
	CONTRAAMOUNT VARCHAR2(38 BYTE) NULL, 
	ACCOUNTLONGNAME VARCHAR2(100 BYTE) NULL, 
	TAKERBUYSBASE NUMBER(3) NULL, 
	ACCOUNTMNEMONIC VARCHAR2(100 BYTE) NULL, 
	UNIQUETRANSACTIONID VARCHAR2(52 BYTE) NULL, 
	BRANCHLEI VARCHAR2(20 BYTE) NULL, 
	ACCOUNTLEI VARCHAR2(20 BYTE) NULL, 
	CLEARINGBROKER VARCHAR2(4 BYTE) NULL, 
	CLEARINGBROKERLEI VARCHAR2(20 BYTE) NULL, 
	CLEARINGBROKERNAME VARCHAR2(100 BYTE) NULL, 
	SECURITYCONVERSION NUMBER(3) NULL,
	CONTRAACCOUNT VARCHAR2(38) NULL, 
	VENUETRANSID VARCHAR2(100) NULL,
	NPFTFLAG NUMBER(3) DEFAULT -1 NULL,
	BUYER VARCHAR2(20) NULL,
	SELLER VARCHAR2(20) NULL,
	IDMTHIRDPARTYREF VARCHAR2(52) NULL,
	IDMDISPLAYNAME  VARCHAR2(256) NULL,
	TRANSACTIONREF VARCHAR2(52) NULL,
	SECFIN NUMBER(3) DEFAULT -1 NULL,
	CONSTRAINT UN_ALLOCATIONS UNIQUE (DEALID, LOCALTCID, SOURCEREFERENCE, TIMEOFDEAL, ORDERID, ALLOCATIONID)
) TABLESPACE DT_ARCHIVE8N;

 
 CREATE TABLE C##RTR_DT8N.CONVERSATIONSCENTRIC (
	TCID CHAR(4) NULL,
	SOURCEREFERENCE CHAR(11) NOT NULL,
	LOCALTCID CHAR(4) NULL,
	TIMEOFDEAL DATE NOT NULL,
	COMPLIANCEACTIVITYVERSION VARCHAR2(11) NULL,
	COMPLIANCESETUPID VARCHAR2(100) NULL,
	COMPLIANCESETUPREFID VARCHAR2(100) NULL,
	COMPLIANCESETUPNAME VARCHAR2(100) NULL,
	DATAPERIODFROM TIMESTAMP NULL,
	DATAPERIODTO TIMESTAMP NULL,
	OURUSERINFOIDENTIFIER VARCHAR2(100) NULL,
	OURUSERINFOEMAIL VARCHAR2(256) NULL,
	OURUSERINFOLASTNAME VARCHAR2(100) NULL,
	OURSITELOCATIONID CHAR(4) NULL,
	OURSITELOCATIONNAME VARCHAR2(100) NULL,
	THEIRUSERINFOIDENTIFIER VARCHAR2(100) NULL,
	THEIRUSERINFOEMAIL VARCHAR2(256) NULL,
	THEIRUSERINFOLASTNAME VARCHAR2(100) NULL,
	THEIRSITELOCATIONID CHAR(4) NULL,
	THEIRSITELOCATIONNAME VARCHAR2(100) NULL,
	CHATIDENTIFIER VARCHAR2(11) NULL,
	CHATTOPIC VARCHAR2(256) NULL,
	CHATDISCLAIMER VARCHAR2(256) NULL,
	OURPARTICIPANTSUSER VARCHAR2(100) NULL,
	THEIRPARTICIPANTSUSER VARCHAR2(100) NULL,
	XMLCENTRIC XMLTYPE NULL,
	CONSTRAINT UN_CONVERSATIONSCENTRIC UNIQUE (SOURCEREFERENCE, LOCALTCID, TIMEOFDEAL)
) TABLESPACE DT_ARCHIVE8N;
CREATE INDEX C##RTR_DT8N.CONVCENTRIC_SR ON C##RTR_DT8N.CONVERSATIONSCENTRIC(SOURCEREFERENCE) TABLESPACE INDEX_SPACE8N;
CREATE INDEX C##RTR_DT8N.CONVCENTRIC_COVERIDX1 ON C##RTR_DT8N.CONVERSATIONSCENTRIC(SOURCEREFERENCE, TCID, TIMEOFDEAL) TABLESPACE INDEX_SPACE8N;
CREATE INDEX C##RTR_DT8N.CONVCENTRIC_TOD ON C##RTR_DT8N.CONVERSATIONSCENTRIC(TIMEOFDEAL) TABLESPACE INDEX_SPACE8N;
CREATE INDEX C##RTR_DT8N.CONVCENTRIC_LOCALTCID ON C##RTR_DT8N.CONVERSATIONSCENTRIC(LOCALTCID) TABLESPACE INDEX_SPACE8N;

CREATE TABLE C##RTR_DT8N.RATESOURCES(
	DEALID CHAR(15) NOT NULL,
	LOCALTCID CHAR(4) NOT NULL,
	SOURCEREFERENCE CHAR(11) NOT NULL,
	TIMEOFDEAL DATE NOT NULL,
	ORDERID VARCHAR2(100) NOT NULL,
	RATESOURCEID VARCHAR2(30) NOT NULL,
	RATESOURCE VARCHAR2(256) NULL,
	FIXINGDATE DATE NULL,
	REFERENCEPAGE VARCHAR2(256) NULL,
	FIXINGCENTER VARCHAR2(256) NULL,
	RATESOURCETEXT VARCHAR2(256) NULL,
	CONSTRAINT UN_RATESOURCES UNIQUE (DEALID, LOCALTCID, SOURCEREFERENCE, TIMEOFDEAL, ORDERID, RATESOURCEID)
) TABLESPACE DT_ARCHIVE8N;


CREATE TABLE C##RTR_DT8N.TBTRADEREPORT(
    REPORTID NUMBER(18,0) NOT NULL,
    USERID VARCHAR2(255) NULL,
    REPORTON NUMBER(3) DEFAULT 0 NULL,
    SHOWING NUMBER(3) DEFAULT 0 NULL,
    DETAILLEVEL NUMBER(3) DEFAULT 0 NULL, 
    TCIDFILTER CLOB NULL,
    TRADERFILTER CLOB NULL,
    GROUPBY CLOB NULL,
    SORTBY CLOB NULL,
    SORTDIRECTION NUMBER(3) DEFAULT 0 NULL,
    DETAILFIELDS CLOB NULL,
    REPORTTO  NUMBER(3) DEFAULT 0 NULL
) TABLESPACE DT_ARCHIVE8N;
ALTER TABLE C##RTR_DT8N.TBTRADEREPORT ADD CONSTRAINT PK_TBTRADEREPORT PRIMARY KEY (REPORTID);


CREATE GLOBAL TEMPORARY TABLE C##RTR_DT8N.TEMPORARY_CONV_TEXT(
  CONVERSATIONTEXT  CLOB NULL
) ON COMMIT DELETE ROWS;



CREATE SEQUENCE C##RTR_DT8N.SEQUENCE_TBSEARCHFIELD_ID
START WITH 1
INCREMENT BY 1
NOCACHE
;


CREATE SEQUENCE C##RTR_DT8N.SEQUENCE_TBSEARCH_SEARCHID
START WITH 1
INCREMENT BY 1
NOCACHE
;


CREATE SEQUENCE C##RTR_DT8N.SEQUENCE_TBTRADEREPORT_REPORTID
START WITH 1
INCREMENT BY 1
NOCACHE
;


-- Run Store Procedure
@@ Procedure_Oracle_861.sql;


CREATE OR REPLACE TRIGGER C##RTR_DT8N.TRG_INCREMENTSEARCHFIELDID
BEFORE INSERT
ON C##RTR_DT8N.TBSEARCHFIELD
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
SELECT  SEQUENCE_TBSEARCHFIELD_ID.nextval INTO :NEW.ID FROM DUAL;
END;
/


CREATE OR REPLACE TRIGGER C##RTR_DT8N.TRG_INCREMENTSEARCHID
BEFORE INSERT
ON C##RTR_DT8N.TBSEARCH
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
SELECT  SEQUENCE_TBSEARCH_SEARCHID.nextval INTO :NEW.SEARCHID FROM DUAL;
END;
/


CREATE OR REPLACE TRIGGER C##RTR_DT8N.TRG_INCREMENTREPORTID
BEFORE INSERT
ON C##RTR_DT8N.TBTRADEREPORT
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
SELECT  SEQUENCE_TBTRADEREPORT_REPORTID.nextval INTO :NEW.REPORTID FROM DUAL;
END;
/


CREATE OR REPLACE TRIGGER C##RTR_DT8N.AUTOCHECKTICKETSFORTCIDS
BEFORE INSERT 
ON C##RTR_DT8N.TICKETS
REFERENCING  NEW AS NEW
FOR EACH ROW 
DECLARE n_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO n_Count FROM tbCheckTicketsTCIDs WHERE LocalTCID = :NEW.LOCALTCID;
IF (n_Count > 0 AND (:new.SourceOfData = 2 OR :new.SourceOfData = 4)) THEN
:NEW.Processed := 1;
:NEW.ProcessedBy := 'System';
:NEW.ProcessedAt :=  SYSDATE;
:NEW.Processed2 := 1;
:NEW.Processed2By := 'System';
:NEW.Processed2At :=  SYSDATE;
:NEW.LastModifiedBy :=  'System';
:NEW.LastModifiedAt :=  SYSDATE;
END IF;
END;
/


CREATE OR REPLACE TRIGGER C##RTR_DT8N.CONVINSERTEDTRIGGER
BEFORE INSERT 
ON C##RTR_DT8N.CONVERSATIONS
REFERENCING NEW AS NEW
FOR EACH ROW 
DECLARE 
N_COUNT INTEGER; 
N_GENTICKET INTEGER := 0;
N_TICKETID NUMBER(10,0);
STR_TICKET_DEALID VARCHAR2(15);
N_CHECK1 NUMBER(3) := 0;
STR_CHECK1BY VARCHAR2(50) := NULL;
N_CHECK2 NUMBER(3) := 0;
STR_CHECK2BY VARCHAR2(50) := NULL;
N_TICKET_PUREDEALTYPE NUMBER(10);
DT_CURRENTDATE DATE;
DT_CURRENTDATE_UTC DATE;
DT_PROCESSED1DATE DATE := NULL;
DT_PROCESSED2DATE DATE := NULL;
STR_SQL VARCHAR2(32767);
BEGIN
  SELECT SYSDATE INTO DT_CURRENTDATE FROM DUAL;
  SELECT SYS_EXTRACT_UTC(SYSTIMESTAMP) INTO DT_CURRENTDATE_UTC FROM DUAL;

  SELECT COUNT(*) INTO N_COUNT FROM TBAUTOCHECKNODEALTCIDS WHERE LOCALTCID = :NEW.LOCALTCID;
  
  --DBMS_OUTPUT.PUT_LINE('COUNT NODEAL = ' || N_COUNT);
  IF (N_COUNT > 0)
  THEN
    IF(:NEW.DEALTYPE IS NULL OR :NEW.DEALTYPE = 0 OR :NEW.DEALVOLUMECURRENCY1 IS NULL OR :NEW.DEALVOLUMECURRENCY1 = 0 )
    THEN
      :NEW.NODEAL := 1;
      :NEW.NODEALEDBY := 'System';
      NULL;
    END IF;
  ELSIF (:NEW.DEALERID IS NOT NULL AND :NEW.DEALERID NOT IN ('DTPSP'))
  THEN
    SELECT COUNT(*) INTO N_COUNT from TBAUTOTICKETSGENERATIONTCIDS where LOCALTCID = :NEW.LOCALTCID;
    --DBMS_OUTPUT.PUT_LINE('COUNT AUTOGEN TCID = ' || N_COUNT);
    IF (N_COUNT > 0) 
    THEN 
      -- check mandatory field for full ticket 
      IF( (:NEW.PUREDEALTYPE IN (2,4,128) AND :NEW.DEALVOLUMECURRENCY1 <> 0 AND :NEW.CURRENCY1 IS NOT NULL AND :NEW.CURRENCY2  IS NOT NULL AND :NEW.DEALTYPE > 0 AND :NEW.EXCHANGERATEPERIOD1 <> 0 AND :NEW.VALUEDATEPERIOD1CURRENCY1 IS NOT NULL AND :NEW.VALUEDATEPERIOD1CURRENCY2 IS NOT NULL) 
      OR (:NEW.PUREDEALTYPE = 8 AND :NEW.DEALVOLUMECURRENCY1 <> 0 AND :NEW.CURRENCY1  IS NOT NULL AND :NEW.CURRENCY2  IS NOT NULL AND :NEW.DEALTYPE > 0 AND :NEW.EXCHANGERATEPERIOD1 <> 0 AND :NEW.EXCHANGERATEPERIOD2 <> 0 AND :NEW.SWAPRATE <> 0 AND :NEW.VALUEDATEPERIOD1CURRENCY1 IS NOT NULL AND :NEW.VALUEDATEPERIOD1CURRENCY2 IS NOT NULL AND :NEW.VALUEDATEPERIOD2CURRENCY1 IS NOT NULL AND :NEW.VALUEDATEPERIOD2CURRENCY2 IS NOT NULL) 
      OR (:NEW.PUREDEALTYPE = 13 AND :NEW.DEALVOLUMECURRENCY1 <> 0 AND :NEW.CURRENCY1  IS NOT NULL AND :NEW.DEALTYPE > 0 AND :NEW.DEPOSITRATE <> 0 AND :NEW.VALUEDATEPERIOD1CURRENCY1 IS NOT NULL AND :NEW.VALUEDATEPERIOD2CURRENCY1 IS NOT NULL) 
	  OR (:NEW.PUREDEALTYPE = 16 AND :NEW.DEALVOLUMECURRENCY1 <> 0 AND :NEW.CURRENCY1  IS NOT NULL AND :NEW.DEALTYPE > 0 AND :NEW.DEPOSITRATE <> 0 AND :NEW.VALUEDATEPERIOD1CURRENCY1 IS NOT NULL AND :NEW.VALUEDATEPERIOD2CURRENCY1 IS NOT NULL) 
      OR (:NEW.PUREDEALTYPE = 32 AND :NEW.DEALVOLUMECURRENCY1 <> 0 AND :NEW.CURRENCY1  IS NOT NULL AND :NEW.DEALTYPE > 0 AND :NEW.DEPOSITRATE <> 0 AND :NEW.FRAFIXINGDATE IS NOT NULL AND :NEW.FRASETTLEMENTDATE IS NOT NULL AND :NEW.FRAMATURITYDATE IS NOT NULL) 
		OR (:NEW.PUREDEALTYPE IN (9,10)  AND :NEW.DEALVOLUMECURRENCY1 <> 0 AND :NEW.CURRENCY1 IS NOT NULL AND
							:NEW.STARTDATE IS NOT NULL AND :NEW.ENDDATE IS NOT NULL AND
							:NEW.INTERESTDAYBASIS IS NOT NULL AND :NEW.RESETFREQUENCY <> 0 AND :NEW.INDEX1 IS NOT NULL)
		OR (:NEW.PUREDEALTYPE = 7 AND :NEW.DEALTYPE > 0 AND :NEW.DEALVOLUMECURRENCY1 <> 0 AND 
							:NEW.CURRENCY1 IS NOT NULL AND :NEW.CURRENCY2 IS NOT NULL AND
							:NEW.EXCHANGERATEPERIOD1 <> 0 AND 
							:NEW.DELIVERYDATE IS NOT NULL AND :NEW.EXPIRYDATE IS NOT NULL AND
							:NEW.OPTIONTYPE IS NOT NULL AND (:NEW.VOLATILITY > 0 OR :NEW.VOLATILITY2 > 0) AND (:NEW.PREMIUMAMOUNT <> 0 OR :NEW.PREMIUMAMOUNT2 <> 0) AND 
							:NEW.PREMIUMCURRENCY IS NOT NULL AND :NEW.EXPIRYSTYLE <> 0)
		)
      THEN  
        SELECT COUNT(*) INTO N_COUNT FROM COUNTERPARTIES WHERE LOCALTCID = :new.BANK1DEALINGCODE;
        --DBMS_OUTPUT.PUT_LINE('COUNT COUNTERPARTIES = ' || N_COUNT);
        IF(N_COUNT > 0)
        THEN
          N_GENTICKET := 1;
          N_TICKET_PUREDEALTYPE := :NEW.PUREDEALTYPE;
          
          SELECT ATG_CHECK1,ATG_CHECK2 INTO N_CHECK1,N_CHECK2 FROM TBSYSTEMCONFIGURATION;
          
          IF(N_CHECK1 > 0)
          THEN
            STR_CHECK1BY := 'System';
            DT_PROCESSED1DATE := DT_CURRENTDATE;
          END IF;
          
          IF(N_CHECK2 > 0)
          THEN
            STR_CHECK2BY := 'System';
            DT_PROCESSED2DATE := DT_CURRENTDATE;
          END IF;
          
        END IF;
      END IF;
      
      IF(N_GENTICKET = 0)
      THEN
        -- check confirm word and nonstandard word for partial ticket
        SELECT ATG_SQLSTATEMENT INTO STR_SQL FROM TBSYSTEMCONFIGURATION;
        --DBMS_OUTPUT.PUT_LINE('get ATG_STATEMENT = ' || STR_SQL);
        IF(STR_SQL IS NOT NULL)
        THEN
          INSERT INTO TEMPORARY_CONV_TEXT VALUES (:NEW.CONVERSATIONTEXT);
          STR_SQL := 'SELECT COUNT(*) FROM TEMPORARY_CONV_TEXT WHERE ' || STR_SQL;
          --DBMS_OUTPUT.PUT_LINE('get STR_SQL = ' || STR_SQL);
          EXECUTE IMMEDIATE STR_SQL INTO N_COUNT;
          DELETE FROM TEMPORARY_CONV_TEXT;
          --DBMS_OUTPUT.PUT_LINE('COUNT CONV TEXT = ' || N_COUNT);
          IF(N_COUNT > 0)
          THEN
            SELECT COUNT(*) INTO N_COUNT FROM COUNTERPARTIES WHERE LOCALTCID = :NEW.BANK1DEALINGCODE;
            
            IF(N_COUNT > 0)
            THEN
              N_GENTICKET := 2;
              N_TICKET_PUREDEALTYPE := 32000;
            END IF;
          END IF;
        END IF;
      END IF;
    END IF;
          
    IF(N_GENTICKET <> 0)
    THEN
      DTANALYSER_PCK.SP_INCREMENTRUNNINGVALUE(N_TICKETID, 'AutoTicketDealID');
      
      STR_TICKET_DEALID := CAST(N_TICKETID AS VARCHAR2);
      STR_TICKET_DEALID := :NEW.TCID || '#MA' || STR_TICKET_DEALID;
      
      INSERT INTO TICKETS 
		(
			DEALID
			,PROCESSED
			,PROCESSEDBY
			,PROCESSEDAT
			,PROCESSED2
			,PROCESSED2BY
			,PROCESSED2AT
			,LOCALTCID
			,SOURCEREFERENCE
			,TIMEOFDEAL
			,DEALERID
			,PUREDEALTYPE
			,DEALTYPE
			,BANK1DEALINGCODE
			,BROKERDEALINGCODE
			,CURRENCY1
			,CURRENCY2
			,DEALVOLUMECURRENCY1
			,EXCHANGERATEPERIOD1
			,EXCHANGERATEPERIOD2
			,METHODOFDEAL
			,PERIOD1
			,PERIOD2
			,CONFIRMATIONTIME
			,CONFIRMEDBYID
			,BANK1NAME
			,DEPOSITRATE
			,SWAPRATE
			,SOURCEOFDATA
			,RATEDIRECTION
			,VALUEDATEPERIOD1CURRENCY1
			,VALUEDATEPERIOD1CURRENCY2
			,VALUEDATEPERIOD2CURRENCY1
			,VALUEDATEPERIOD2CURRENCY2
			,DEALERNAME
			,REVIEWREFERENCENUMBER
			,BROKERNAME
			,FRAFIXINGDATE
			,FRASETTLEMENTDATE
			,FRAMATURITYDATE
			,IMMINDICATOR
			,OUTRIGHTPOINTSPREMIUMRATE
			,SPOTBASISRATE
			,CONVERSATIONTEXT
			,CONFIRMEDBYNAME
			,IDIFCONTRA
			,IDPREVIOUS
			,AUTOGENERATEDTICKET
			,TransactionID 
			,StartDate
			,EndDate
			,DeliveryDate
			,DeliveryDate2
			,ExpiryDate
			,ExpiryDate2
			,PaymentDate
			,PremiumDate
			,InterestDayBasis
			,InterestDayBasis2
			,Index1
			,Index2
			,ResetFrequency
			,ResetBusinessDayConvention
			,PaymentBusinessDayConvention
			,ResetCalendar
			,PaymentFrequency
			,SecondaryFrequency
			,StubIndicator 
			,StubRate
			,IndexSpread
			,OptionType
			,OptionType2
			,Cutoff
			,Cutoff2
			,ExpiryStyle
			,Direction2
			,TradingStrategy
			,Settlement
			,PremiumAmount
			,PremiumAmount2
			,Volatility
			,Volatility2
			,PremiumQuote
			,PremiumQuote2
			,PremiumCurrency
			,TotalNetPremiumAmount
			,PremiumQuoteConvention
			,HedgeDirection
			,HedgeDirection2
			,HedgeValueDate
			,HedgeValueDate2
			,HedgeAmount
			,HedgeAmount2
			,HedgeContraAmount
			,HedgeContraAmount2
			,HedgeRate
			,HedgeRate2
			,DepositRateReference
			,DepositRateReference2
			,SwapPointsReference
			,SwapPointsReference2
			,SwiftBicC1P1
			,SwiftBicC1P2
			,SwiftBicC2P1
			,SwiftBicC2P2
			,PaymentInstructionP1C1
			,PaymentInstructionP1C2
			,PaymentInstructionP2C1
			,PaymentInstructionP2C2
			,FixedRate
			,CalVolumeP2C1
			,InterestVolume
			,ElapsedDays
			,YearLength
			,PriceConvention
			,ClearingHouse
			,ClearingAccount
			,OurClearingMember
			,TheirClearingMember
			,OnBehalfOfName
			,OnBehalfOfCode
			,PremiumDate2
			,MidPrice
			,BestBid
			,BestAsk
			,OurLEI
			,TheirLEI
			,BrokerageAmount
			,ReportingParty
			,Namespace
			,LinkID
			,TransactionID2
			,TradeRepository
			,BrokerageCurrency
			,CPUserID
			,CPUserName
			,UTI1
			,UTI2
			,OurEmailAddress
			,TheirEmailAddress
			,TRADINGINTERFACE
			,BENCHMARKFIXINGTYPE1
			,BENCHMARKFIXINGDATE1
			,BENCHMARKFIXINGRATE1
			,BENCHMARKFIXINGTYPE2
			,BENCHMARKFIXINGDATE2
			,BENCHMARKFIXINGRATE2
			,OURJURISDICTION
			,THEIRJURISDICTION
			,EXECUTIONVENUETYPE
			,OURCLEARINGBROKER
			,OURCLEARINGBROKERLEI
			,THEIRCLEARINGBROKER
			,THEIRCLEARINGBROKERLEI
			,EXECUTIONID
			,ORDERID	
			,CALLINITTIME
			,ACCEPTTIME
			,CONFIRMEDTIME
			,EXTRACTEDTIME
			,FIRSTENDTIME
			,SECONDENDTIME
			,QUOTETIME
			,QUOTEREJECTTIME
			,AGGRESSORINDICATOR
        ) VALUES (
			STR_TICKET_DEALID			--[DealId]
			,N_CHECK1					--,[Processed]
			,STR_CHECK1BY				--,[ProcessedBy]
			,DT_PROCESSED1DATE			--,[ProcessedAt]
			,N_CHECK2					--,[Processed2]
			,STR_CHECK2BY				--,[Processed2By]
			,DT_PROCESSED2DATE			--,[Processed2At]
			,:NEW.LOCALTCID
			,:NEW.SOURCEREFERENCE		
			,:NEW.TIMEOFDEAL		
			,:NEW.DEALERID			
			,N_TICKET_PUREDEALTYPE		
			,:NEW.DEALTYPE			
			,:NEW.BANK1DEALINGCODE		
			,:NEW.BROKERDEALINGCODE		
			,:NEW.CURRENCY1	
			,CASE WHEN N_TICKET_PUREDEALTYPE IN (2, 21, 64, 4, 128, 8, 7, 32000) then :NEW.CURRENCY2 else NULL end --:NEW.CURRENCY2	
			,:NEW.DEALVOLUMECURRENCY1				
			,:NEW.EXCHANGERATEPERIOD1				
			,:new.EXCHANGERATEPERIOD2				
			,1							--,[MethodOfDeal]
			,:NEW.PERIOD1							
			,:NEW.PERIOD2							
			,DT_CURRENTDATE_UTC			--,[ConfirmationTime]
			,'System'					--,[ConfirmedById]
			,:NEW.BANK1NAME					
			,:NEW.DEPOSITRATE					
			,:new.SWAPRATE						
			,5							--,[SourceOfData]
			,:NEW.RATEDIRECTION	
			,:NEW.VALUEDATEPERIOD1CURRENCY1	
			,:NEW.VALUEDATEPERIOD1CURRENCY2	
			,:NEW.VALUEDATEPERIOD2CURRENCY1	
			,:NEW.VALUEDATEPERIOD2CURRENCY2	
			,:NEW.DEALERNAME				
			,:NEW.REVIEWREFERENCENUMBER		
			,:NEW.BROKERNAME				
			,:NEW.FRAFIXINGDATE			
			,:NEW.FRASETTLEMENTDATE					
			,:NEW.FRAMATURITYDATE						
			,:NEW.IMMINDICATOR						
			,:NEW.OUTRIGHTPOINTSPREMIUMRATE				
			,:NEW.SPOTBASISRATE						
			,:NEW.CONVERSATIONTEXT
			,'System'					--,[ConfirmedByName]
			,:NEW.TCID || '#0'			--,[IDifContra]
			,:NEW.TCID || '#0'			--,[IDPrevious]
			,N_GENTICKET				--,[AutoGenerate]
			,:NEW.TransactionID 
			,:NEW.StartDate
			,:NEW.EndDate
			,:NEW.DeliveryDate
			,:NEW.DeliveryDate2
			,:NEW.ExpiryDate
			,:NEW.ExpiryDate2
			,:NEW.PaymentDate
			,:NEW.PremiumDate
			,:NEW.InterestDayBasis
			,:NEW.InterestDayBasis2
			,:NEW.Index1
			,:NEW.Index2
			,:NEW.ResetFrequency
			,:NEW.ResetBusinessDayConvention
			,:NEW.PaymentBusinessDayConvention
			,:NEW.ResetCalendar
			,:NEW.PaymentFrequency
			,:NEW.SecondaryFrequency
			,:NEW.StubIndicator 
			,:NEW.StubRate
			,:NEW.IndexSpread
			,:NEW.OptionType
			,:NEW.OptionType2
			,:NEW.Cutoff
			,:NEW.Cutoff2
			,:NEW.ExpiryStyle
			,:NEW.Direction2
			,:NEW.TradingStrategy
			,:NEW.Settlement
			,:NEW.PremiumAmount
			,:NEW.PremiumAmount2
			,:NEW.Volatility
			,:NEW.Volatility2
			,:NEW.PremiumQuote
			,:NEW.PremiumQuote2
			,:NEW.PremiumCurrency
			,:NEW.TotalNetPremiumAmount
			,:NEW.PremiumQuoteConvention
			,:NEW.HedgeDirection
			,:NEW.HedgeDirection2
			,:NEW.HedgeValueDate
			,:NEW.HedgeValueDate2
			,:NEW.HedgeAmount
			,:NEW.HedgeAmount2
			,:NEW.HedgeContraAmount
			,:NEW.HedgeContraAmount2
			,:NEW.HedgeRate
			,:NEW.HedgeRate2
			,:NEW.DepositRateReference
			,:NEW.DepositRateReference2
			,:NEW.SwapPointsReference
			,:NEW.SwapPointsReference2
			,:NEW.SwiftBicC1P1
			,:NEW.SwiftBicC1P2
			,:NEW.SwiftBicC2P1
			,:NEW.SwiftBicC2P2
			,:NEW.PaymentInstructionP1C1
			,:NEW.PaymentInstructionP1C2
			,:NEW.PaymentInstructionP2C1
			,:NEW.PaymentInstructionP2C2
			,:NEW.FixedRate
			,:NEW.CalVolumeP2C1
			,:NEW.InterestVolume
			,:NEW.ElapsedDays
			,:NEW.YearLength
			,:NEW.PriceConvention
			,:NEW.ClearingHouse
			,:NEW.ClearingAccount
			,:NEW.OurClearingMember
			,:NEW.TheirClearingMember
			,:NEW.OnBehalfOfName
			,:NEW.OnBehalfOfCode
			,:NEW.PremiumDate2
			,:NEW.MidPrice
			,:NEW.BestBid
			,:NEW.BestAsk
			,:NEW.OurLEI
			,:NEW.TheirLEI
			,:NEW.BrokerageAmount
			,:NEW.ReportingParty
			,:NEW.Namespace
			,:NEW.LinkID
			,:NEW.TransactionID2
			,:NEW.TradeRepository
			,:NEW.BrokerageCurrency
			,:NEW.CPUserID
			,:NEW.CPUserName
			,:NEW.UTI1
			,:NEW.UTI2
			,:NEW.OurEmailAddress
			,:NEW.TheirEmailAddress
			,:NEW.TRADINGINTERFACE
			,:NEW.BENCHMARKFIXINGTYPE1
			,:NEW.BENCHMARKFIXINGDATE1
			,:NEW.BENCHMARKFIXINGRATE1
			,:NEW.BENCHMARKFIXINGTYPE2
			,:NEW.BENCHMARKFIXINGDATE2
			,:NEW.BENCHMARKFIXINGRATE2
			,:NEW.OURJURISDICTION
			,:NEW.THEIRJURISDICTION
			,:NEW.EXECUTIONVENUETYPE
			,:NEW.OURCLEARINGBROKER
			,:NEW.OURCLEARINGBROKERLEI
			,:NEW.THEIRCLEARINGBROKER
			,:NEW.THEIRCLEARINGBROKERLEI
			,:NEW.EXECUTIONID
			,:NEW.ORDERID
			,:NEW.CALLINITTIME
			,:NEW.ACCEPTTIME
			,:NEW.CONFIRMEDTIME
			,:NEW.EXTRACTEDTIME
			,:NEW.FIRSTENDTIME
			,:NEW.SECONDENDTIME
			,:NEW.QUOTETIME
			,:NEW.QUOTEREJECTTIME
			,:NEW.AGGRESSORINDICATOR		
        );
        
      :NEW.TICKETSTATUS := 1;
      :NEW.NODEAL := 0;
    END IF;
  END IF;
END;
/

CREATE OR REPLACE VIEW C##RTR_DT8N.VW_TCIDTICKETS AS 
  SELECT DISTINCT LocalTCID, Bank1DealingCode FROM TICKETS ;
/

CREATE OR REPLACE VIEW C##RTR_DT8N.VW_POSSIBLEDUPLICATES  AS 
SELECT TimeOfDeal,SourceReference,LocalTCID
FROM Tickets  
GROUP BY TimeOfDeal, SourceReference, LocalTCID 
HAVING Count(*)>1 AND Sum(DECODE(SourceOfData,5,1,0))>=1  ; 
/

@@ Cpty_Oracle_861.sql;

@@ ClearingHouse_Oracle_861.sql;

SET TIMING OFF

