-- Support Oracle database Grant role to user script     
--  
-- Version: 8.6.1
-- Internal Version: 8.6.1.2
-- 
-- Edit History:
--  
-- Date         IssueID             Fix          	Reason
-- ==========   ==================  ===========  	====================================================
-- 19/05/2022	DTS_DT853			Surachai C.		[DTS_DT853] DT/MT 8.5.3
-- 17/10/2022	DTS_DT861			Surachai C.		[DTS_DT861] DT/MT 8.6.1


SET TIMING ON;
WHENEVER OSERROR EXIT FAILURE ROLLBACK;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
SET SERVEROUTPUT ON

-- User Account
DECLARE
  username_val varchar2(50);
BEGIN
   DBMS_OUTPUT.PUT_LINE('Check user account if exist then skip for create new.');
   SELECT username INTO username_val FROM all_users WHERE username=UPPER('&1');
   EXCEPTION
   WHEN NO_DATA_FOUND THEN 
		DBMS_OUTPUT.PUT_LINE('No user found then create user: &1');   
		execute immediate 'CREATE USER &1 IDENTIFIED BY "reut" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP';
		execute immediate 'GRANT CONNECT TO &1';
END;
/


-- Check Role 
DECLARE
  role_val varchar2(50);
BEGIN
   DBMS_OUTPUT.PUT_LINE('Check role if exist then skip for create new.');
   SELECT ROLE INTO role_val FROM DBA_ROLES where ROLE='RTR_DT8N_OBJ_RW_ROLE';
   EXCEPTION
   WHEN NO_DATA_FOUND THEN
	DBMS_OUTPUT.PUT_LINE('No role found then create role: RTR_DT8N_OBJ_RW_ROLE');   
	execute immediate 'CREATE ROLE RTR_DT8N_OBJ_RW_ROLE NOT IDENTIFIED';
END;
/


GRANT RTR_DT8N_OBJ_RW_ROLE TO &1;


-- Grant table to user account
GRANT CREATE JOB TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RTR_DT8N.TICKETS TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RTR_DT8N.CALLS TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RTR_DT8N.COUNTERPARTIES TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RTR_DT8N.USERS TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RTR_DT8N.REPORTS TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RTR_DT8N.VERSION TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RTR_DT8N.TBUSERAUDIT TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RTR_DT8N.TBAUTOCHECKNODEALTCIDS TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RTR_DT8N.TBLOGINLOG TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RTR_DT8N.TBTRADELOG TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RTR_DT8N.TBADMINLOG TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RTR_DT8N.TBSYSTEMCONFIGURATION TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RTR_DT8N.TBSOURCEOFDATA TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RTR_DT8N.TBPUREDEALTYPE TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RTR_DT8N.TBDEALTYPE TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RTR_DT8N.TBCUSTOMDEALINGFIELDS TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RTR_DT8N.TBCHECKTICKETSTCIDS TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RTR_DT8N.TBUSERTCIDDEALEREXCEPTIONLIST TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RTR_DT8N.TBSEARCH TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RTR_DT8N.TBSEARCHFIELD TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RTR_DT8N.TBMYLINKSPERSONALIZATION TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RTR_DT8N.CONVERSATIONS TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RTR_DT8N.TBRUNNINGNUMBER TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RTR_DT8N.TBAUTOTICKETSGENERATIONTCIDS TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RTR_DT8N.VERSIONTHIRDPARTY TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RTR_DT8N.TBCLEARINGHOUSE TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RTR_DT8N.TBUSERCUSTOMIZEVIEW TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RTR_DT8N.TBROLES TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RTR_DT8N.ALLOCATIONS TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RTR_DT8N.TBUSERDEFINED TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RTR_DT8N.CONVERSATIONSCENTRIC TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RTR_DT8N.RATESOURCES TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RTR_DT8N.TBTRADEREPORT TO RTR_DT8N_OBJ_RW_ROLE;

-- Create SYNONYM for table
CREATE OR REPLACE SYNONYM &1.."TICKETS" FOR "RTR_DT8N"."TICKETS";
CREATE OR REPLACE SYNONYM &1.."CALLS" FOR "RTR_DT8N"."CALLS";
CREATE OR REPLACE SYNONYM &1.."COUNTERPARTIES" FOR "RTR_DT8N"."COUNTERPARTIES";
CREATE OR REPLACE SYNONYM &1.."USERS" FOR "RTR_DT8N"."USERS";
CREATE OR REPLACE SYNONYM &1.."REPORTS" FOR "RTR_DT8N"."REPORTS";
CREATE OR REPLACE SYNONYM &1.."VERSION" FOR "RTR_DT8N"."VERSION";
CREATE OR REPLACE SYNONYM &1.."TBUSERAUDIT" FOR "RTR_DT8N"."TBUSERAUDIT";
CREATE OR REPLACE SYNONYM &1.."TBAUTOCHECKNODEALTCIDS" FOR "RTR_DT8N"."TBAUTOCHECKNODEALTCIDS";
CREATE OR REPLACE SYNONYM &1.."TBLOGINLOG" FOR "RTR_DT8N"."TBLOGINLOG";
CREATE OR REPLACE SYNONYM &1.."TBTRADELOG" FOR "RTR_DT8N"."TBTRADELOG";
CREATE OR REPLACE SYNONYM &1.."TBADMINLOG" FOR "RTR_DT8N"."TBADMINLOG";
CREATE OR REPLACE SYNONYM &1.."TBSYSTEMCONFIGURATION" FOR "RTR_DT8N"."TBSYSTEMCONFIGURATION";
CREATE OR REPLACE SYNONYM &1.."TBSOURCEOFDATA" FOR "RTR_DT8N"."TBSOURCEOFDATA";
CREATE OR REPLACE SYNONYM &1.."TBPUREDEALTYPE" FOR "RTR_DT8N"."TBPUREDEALTYPE";
CREATE OR REPLACE SYNONYM &1.."TBDEALTYPE" FOR "RTR_DT8N"."TBDEALTYPE";
CREATE OR REPLACE SYNONYM &1.."TBCUSTOMDEALINGFIELDS" FOR "RTR_DT8N"."TBCUSTOMDEALINGFIELDS";
CREATE OR REPLACE SYNONYM &1.."TBCHECKTICKETSTCIDS" FOR "RTR_DT8N"."TBCHECKTICKETSTCIDS";
CREATE OR REPLACE SYNONYM &1.."TBUSERTCIDDEALEREXCEPTIONLIST" FOR "RTR_DT8N"."TBUSERTCIDDEALEREXCEPTIONLIST";
CREATE OR REPLACE SYNONYM &1.."TBSEARCH" FOR "RTR_DT8N"."TBSEARCH";
CREATE OR REPLACE SYNONYM &1.."TBSEARCHFIELD" FOR "RTR_DT8N"."TBSEARCHFIELD";
CREATE OR REPLACE SYNONYM &1.."TBMYLINKSPERSONALIZATION" FOR "RTR_DT8N"."TBMYLINKSPERSONALIZATION";
CREATE OR REPLACE SYNONYM &1.."CONVERSATIONS" FOR "RTR_DT8N"."CONVERSATIONS";
CREATE OR REPLACE SYNONYM &1.."TBRUNNINGNUMBER" FOR "RTR_DT8N"."TBRUNNINGNUMBER";
CREATE OR REPLACE SYNONYM &1.."TBAUTOTICKETSGENERATIONTCIDS" FOR "RTR_DT8N"."TBAUTOTICKETSGENERATIONTCIDS";
CREATE OR REPLACE SYNONYM &1.."VERSIONTHIRDPARTY" FOR "RTR_DT8N"."VERSIONTHIRDPARTY";
CREATE OR REPLACE SYNONYM &1.."TBCLEARINGHOUSE" FOR "RTR_DT8N"."TBCLEARINGHOUSE";
CREATE OR REPLACE SYNONYM &1.."TBUSERCUSTOMIZEVIEW" FOR "RTR_DT8N"."TBUSERCUSTOMIZEVIEW";
CREATE OR REPLACE SYNONYM &1.."TBROLES" FOR "RTR_DT8N"."TBROLES";
CREATE OR REPLACE SYNONYM &1.."ALLOCATIONS" FOR "RTR_DT8N"."ALLOCATIONS";
CREATE OR REPLACE SYNONYM &1.."TBUSERDEFINED" FOR "RTR_DT8N"."TBUSERDEFINED";
CREATE OR REPLACE SYNONYM &1.."CONVERSATIONSCENTRIC" FOR "RTR_DT8N"."CONVERSATIONSCENTRIC";
CREATE OR REPLACE SYNONYM &1.."RATESOURCES" FOR "RTR_DT8N"."RATESOURCES";
CREATE OR REPLACE SYNONYM &1.."TBTRADEREPORT" FOR "RTR_DT8N"."TBTRADEREPORT";

-- Grant view
GRANT SELECT ON RTR_DT8N.VW_TCIDTICKETS TO RTR_DT8N_OBJ_RW_ROLE;
GRANT SELECT ON RTR_DT8N.VW_POSSIBLEDUPLICATES TO RTR_DT8N_OBJ_RW_ROLE;
CREATE OR REPLACE SYNONYM &1.."VW_TCIDTICKETS" FOR "RTR_DT8N"."VW_TCIDTICKETS";
CREATE OR REPLACE SYNONYM &1.."VW_POSSIBLEDUPLICATES" FOR "RTR_DT8N"."VW_POSSIBLEDUPLICATES";

-- Grant Package
GRANT EXECUTE ON RTR_DT8N.DTANALYSER_PCK TO RTR_DT8N_OBJ_RW_ROLE;
CREATE OR REPLACE SYNONYM &1.."DTANALYSER_PCK" FOR "RTR_DT8N"."DTANALYSER_PCK";

-- Grant Function
GRANT EXECUTE ON RTR_DT8N.FN_GETNEXTDAY TO RTR_DT8N_OBJ_RW_ROLE;
CREATE OR REPLACE SYNONYM &1.."FN_GETNEXTDAY" FOR "RTR_DT8N"."FN_GETNEXTDAY";


SET TIMING OFF;